### ISSUE TITLE
java.lang.ClassNotFoundException，yarn模式需要将多个dlink包添加到hdfs

### ISSUE THREAD

**Issue by ghost** [DataLinkDC/dinky#1025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

dlink-0.6.7rc2
flink-1.14.4
hadoop-3.3.1
yarn-application提交

多次报错：Caused by: java.lang.ClassNotFoundException...
需要将多个dlink包加入hdfs/flin/lib才能解决（我不知道原因，每报一次错，我找报错类对应的包加入hdfs），以下是包列表：
![图片](https://user-images.githubusercontent.com/40230796/190575021-6e67bf79-4095-4c93-8342-5babbdce1ddb.png)

以下日志详情：
2879 [flink-akka.actor.default-dispatcher-16] WARN  org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap  - Application failed unexpectedly: 
java.util.concurrent.CompletionException: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:957)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:287)
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$2(ApplicationDispatcherBootstrap.java:224)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	... 13 more
Caused by: java.lang.NoClassDefFoundError: comink/utils/FlinkBaseUtil
	at com.dlink.app.MainApp.main(MainApp.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:261)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.dlink.utils.FlinkBaseUtil
其他日志：
Caused by: java.lang.ClassNotFoundException: com.dlink.executor.ExecutorSetting
...
Caused by: java.lang.ClassNotFoundException: com.dlink.assertion.Asserts
...
Caused by: java.lang.ClassNotFoundException: com.dlink.executor.CustomTableEnvironmentImpl
...

### What you expected to happen

No clue

### How to reproduce

dlink-0.6.7rc2
flink-1.14.4
hadoop-3.3.1
yarn-application提交

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ghost** [comment]
是我flink配置的问题，我将提交FlinkSQL的Jar文件路径配置成了dlink-app-1.14-0.6.7.jar，应配置为dlink-app-1.14-0.6.7-jar-with-dependencies.jar
