### ISSUE TITLE
flink application  on kubernetes ,can not auto create k8s namespace and set kubernetes.cluster-id  not work

### ISSUE THREAD

**Issue by huangkaiyan10** [DataLinkDC/dinky#1115]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

i read  https://cloud.tencent.com/developer/article/1973777  and want  use dinky develop flinksql and summit to k8s ,to test Kubernetes Native Application.
![Uploading image.png…]()
   

Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://apiserver.cluster.local:6443/apis/apps/v1/namespaces/znyw-base-flink-nactive-application/deployments. Message: Deployment.apps "flinksql_test_2" is invalid: metadata.name: Invalid value: "flinksql_test_2": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "flinksql_test_2": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=flinksql_test_2, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "flinksql_test_2" is invalid: metadata.name: Invalid value: "flinksql_test_2": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:673)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:560)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:521)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:309)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:776)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:351)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:90)
        at org.apache.flink.kubernetes.kubeclient.Fabric8FlinkKubeClient.createJobManagerComponent(Fabric8FlinkKubeClient.java:120)
        at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployClusterInternal(KubernetesClusterDescriptor.java:276)

### What you expected to happen

auto create k8s namespace and success deploy flink app(k8s pod) to kubernetes .

### How to reproduce

dinky 0.6.7
flink1.14.6-2.11-java8
k8s 1.19.14

### Version

0.6.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huangkaiyan10** [comment]
[dlink] 2022-10-18 11:38:05 CST INFO  org.apache.flink.kubernetes.utils.KubernetesUtils 101 checkAndUpdatePortConfigOption - Kubernetes deployment requires a fixed port. Configuration blob.server.port will be set to 6124
[dlink] 2022-10-18 11:38:05 CST INFO  org.apache.flink.kubernetes.utils.KubernetesUtils 101 checkAndUpdatePortConfigOption - Kubernetes deployment requires a fixed port. Configuration taskmanager.rpc.port will be set to 6122
[dlink] 2022-10-18 11:38:05 CST WARN  org.apache.flink.kubernetes.KubernetesClusterDescriptor 281 deployClusterInternal - Failed to create the Kubernetes cluster "flinksql_test_2", try to clean up the residual resources.
[dlink] 2022-10-18 11:38:05 CST ERROR com.dlink.utils.LogUtil 46 getError - org.apache.flink.client.deployment.ClusterDeploymentException: Could not create Kubernetes cluster "flinksql_test_2".
        at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployClusterInternal(KubernetesClusterDescriptor.java:291)
        at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployApplicationCluster(KubernetesClusterDescriptor.java:210)
        at com.dlink.gateway.kubernetes.KubernetesApplicationGateway.submitJar(KubernetesApplicationGateway.java:91)
        at com.dlink.job.JobManager.submitByGateway(JobManager.java:432)
        at com.dlink.job.JobManager.executeSql(JobManager.java:324)
        at com.dlink.service.impl.TaskServiceImpl.submitTask(TaskServiceImpl.java:202)
        at com.dlink.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$168bea78.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at com.dlink.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$9e5529f2.submitTask(<generated>)
        at com.dlink.controller.TaskController.submit(TaskController.java:120)
        at com.dlink.controller.TaskController$$FastClassBySpringCGLIB$$a86993b6.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

**Comment by aiwenmo** [comment]
Deployment.apps "flinksql_test_2" is invalid: metadata.name: Invalid value: "flinksql_test_2": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9](https://github.com/DataLinkDC/dlink/issues/%5B-a-z0-9%5D*%5Ba-z0-9%5D)?(.[a-z0-9](https://github.com/DataLinkDC/dlink/issues/%5B-a-z0-9%5D*%5Ba-z0-9%5D)?)').
