### ISSUE TITLE
[Bug] [dlink-core] Lineage generate throw NPE when flinksql contains kafka statement.

### ISSUE THREAD

**Issue by wellCh4n** [DataLinkDC/dinky#1192]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Verison is 0.67**

My demo statement
```
CREATE TABLE ST (
    a STRING,
    b STRING,
    c STRING
) WITH (
  'connector' = 'kafka',
  'topic' = 'st',
  'properties.bootstrap.servers' = 'localhost:9092',
  'properties.group.id' = 'testGroup',
  'scan.startup.mode' = 'earliest-offset',
  'format' = 'json'
);
CREATE TABLE TT (
  A STRING,
  B STRING
) WITH (
 'connector' = 'print'
);
insert into TT select a||c A ,b||c B from ST
```

Console
```
java.lang.NullPointerException
	at com.dlink.explainer.trans.SourceTrans.translate(SourceTrans.java:100)
	at com.dlink.explainer.trans.AbstractTrans.build(AbstractTrans.java:55)
	at com.dlink.explainer.trans.TransGenerator.translateTrans(TransGenerator.java:81)
	at com.dlink.explainer.Explainer.translateTrans(Explainer.java:496)
	at com.dlink.explainer.Explainer.explainSqlColumnCA(Explainer.java:374)
	at com.dlink.plus.FlinkSqlPlus.explainSqlColumnCA(FlinkSqlPlus.java:108)
	at com.dlink.explainer.lineage.LineageBuilder.getLineage(LineageBuilder.java:49)
	at com.dlink.explainer.lineage.LineageBuilder.getLineage(LineageBuilder.java:44)
	at com.dlink.core.LineageTest.sumTest(LineageTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

### What you expected to happen

Normal parsing of kafka's lineage.

### How to reproduce

See the demo statment.

### Anything else

I looked at the code and found that Dlink's lineage is split by Plan's content.
But there are some datasources that translate through Plan and the content is not like 'table=[[xxxx]]', for example Kafka is 'KafkaSource-xxxx', the table and field cannot be parsed by the string, resulting in a null pointer exception in 'com.dlink.explainer.trans.SourceTrans#translate'.

### Version

0.6.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please enable the use of logical plan to resolve blood relationship in the system configuration.

**Comment by wellCh4n** [comment]
> Please enable the use of logical plan to resolve blood relationship in the system configuration.

AWESOME !!! Solved my problem. Thank you very much!
And... I see only supports 1.14, does 1.15 have this problem?

**Comment by aiwenmo** [comment]
> > Please enable the use of logical plan to resolve blood relationship in the system configuration.
> 
> AWESOME !!! Solved my problem. Thank you very much! And... I see only supports 1.14, does 1.15 have this problem?

The implementation of other versions can be extended.
