### ISSUE TITLE
[Bug] 新建flink kubernetes native集群失败

### ISSUE THREAD

**Issue by 804e** [DataLinkDC/dinky#1541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

[](url)新建flink kubernetes native集群配置，点击测试按钮发现报空指针异常
```
Caused by: java.lang.NullPointerException
	at com.dlink.service.impl.ClusterConfigurationServiceImpl.getClusterConfigById(ClusterConfigurationServiceImpl.java:66) ~[dlink-admin-0.7.0.jar:?]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl.testGateway(ClusterConfigurationServiceImpl.java:117) ~[dlink-admin-0.7.0.jar:?]
```
查看代码发现其用一个id去获取docker配置，但是这个id新建是不存在的
https://github.com/DataLinkDC/dinky/blob/f1e232c957d59059e57c9035326b8886a7058387/dlink-admin/src/main/java/com/dlink/service/impl/ClusterConfigurationServiceImpl.java#L116-L120

### What you expected to happen

能正常新建集群配置

### How to reproduce

新建flink kubernetes native集群配置即可重现

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
先注册集群配置

**Comment by 804e** [comment]
> 先注册集群配置

我就是在注册集群配置的时候出问题，我把代码修改后测试正常了，但是新建session的时候又抛出了个空指针
```
Caused by: java.lang.NullPointerException
	at org.apache.flink.configuration.ConfigurationUtils.convertToString(ConfigurationUtils.java:388)
	at org.apache.flink.configuration.ConfigurationUtils.lambda$convertToString$11(ConfigurationUtils.java:396)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.apache.flink.configuration.ConfigurationUtils.convertToString(ConfigurationUtils.java:397)
	at org.apache.flink.configuration.Configuration.toMap(Configuration.java:741)
	at org.apache.flink.configuration.ConfigurationUtils.getPrefixedKeyValuePairs(ConfigurationUtils.java:268)
	at org.apache.flink.kubernetes.kubeclient.parameters.KubernetesJobManagerParameters.getEnvironments(KubernetesJobManagerParameters.java:84)
	at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.getCustomizedEnvs(InitJobManagerDecorator.java:174)
	at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateMainContainer(InitJobManagerDecorator.java:145)
	at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateFlinkPod(InitJobManagerDecorator.java:100)
	at org.apache.flink.kubernetes.kubeclient.factory.KubernetesJobManagerFactory.buildKubernetesJobManagerSpecification(KubernetesJobManagerFactory.java:79)
	at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployClusterInternal(KubernetesClusterDescriptor.java:273)
```
但是我手动创建是没问题的
```
[root@base01 flink-1.14.6]# ./bin/kubernetes-session.sh \
>   -Dkubernetes.namespace=flink \
>   -Dkubernetes.jobmanager.service-account=flink \
>   -Dkubernetes.cluster-id=period-flink-session \
>   -Dtaskmanager.memory.process.size=4096m \
>   -Dkubernetes.taskmanager.cpu=1 \
>   -Dtaskmanager.numberOfTaskSlots=4 \
>   -Dresourcemanager.taskmanager-timeout=3600000
2023-01-12 17:08:41,471 INFO  org.apache.flink.configuration.GlobalConfiguration           [] - Loading configuration property: jobmanager.rpc.address, localhost
2023-01-12 17:08:41,474 INFO  org.apache.flink.configuration.GlobalConfiguration           [] - Loading configuration property: jobmanager.rpc.port, 6123
2023-01-12 17:08:41,474 INFO  org.apache.flink.configuration.GlobalConfiguration           [] - Loading configuration property: jobmanager.memory.process.size, 1600m
2023-01-12 17:08:41,474 INFO  org.apache.flink.configuration.GlobalConfiguration           [] - Loading configuration property: taskmanager.memory.process.size, 1728m
2023-01-12 17:08:41,474 INFO  org.apache.flink.configuration.GlobalConfiguration           [] - Loading configuration property: taskmanager.numberOfTaskSlots, 1
2023-01-12 17:08:41,474 INFO  org.apache.flink.configuration.GlobalConfiguration           [] - Loading configuration property: parallelism.default, 1
2023-01-12 17:08:41,474 INFO  org.apache.flink.configuration.GlobalConfiguration           [] - Loading configuration property: jobmanager.execution.failover-strategy, region
2023-01-12 17:08:41,520 INFO  org.apache.flink.client.deployment.DefaultClusterClientServiceLoader [] - Could not load factory due to missing dependencies.
2023-01-12 17:08:42,781 INFO  org.apache.flink.runtime.util.config.memory.ProcessMemoryUtils [] - The derived from fraction jvm overhead memory (160.000mb (167772162 bytes)) is less than its min value 192.000mb (201326592 bytes), min value will be used instead
2023-01-12 17:08:42,988 INFO  org.apache.flink.kubernetes.utils.KubernetesUtils            [] - Kubernetes deployment requires a fixed port. Configuration blob.server.port will be set to 6124
2023-01-12 17:08:42,989 INFO  org.apache.flink.kubernetes.utils.KubernetesUtils            [] - Kubernetes deployment requires a fixed port. Configuration taskmanager.rpc.port will be set to 6122
2023-01-12 17:08:44,115 INFO  org.apache.flink.kubernetes.KubernetesClusterDescriptor      [] - Create flink session cluster period-flink-session successfully, JobManager Web Interface: http://172.19.0.110:8081
```

**Comment by zackyoungh** [comment]
之前已经修复 k8s npe这个bug，详细请看 #1507
