### ISSUE TITLE
[Bug] [0.7.1] 整库同步至Kafka报错

### ISSUE THREAD

**Issue by yuzq24** [DataLinkDC/dinky#1680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本： 
Dinky 0.7.1
Flink CDC 2.2.1 
Flink 1.13.6

详细：
Dinky提交任务成功
Flink 报错类冲突导致程序无法正常运行

[2023-02-24 17:42:22.644] [INFO ] [flink-akka.actor.default-dispatcher-17] org.apache.flink.runtime.executiongraph.ExecutionGraph(transitionState:1446) 1234688  - Source: MySQL CDC Source -> Sink: Unnamed (1/1) (f466592bb4130c2d193f7e53dbf159b8) switched from RUNNING to FAILED on container_e3016_1677224871933_0004_01_000004 @ master (dataPort=45972).
java.lang.AbstractMethodError: com.dlink.cdc.mysql.MysqlJsonDebeziumDeserializationSchema.deserialize(Lcom/ververica/cdc/connectors/shaded/org/apache/kafka/connect/source/SourceRecord;Lorg/apache/flink/util/Collector;)V
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitElement(MySqlRecordEmitter.java:118)
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:100)
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:54)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:128)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:305)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:684)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:639)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:623)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.lang.Thread.run(Thread.java:748)

### What you expected to happen

Dinky代码
dinky-client-1.13中MysqlJsonDebeziumDeserializationSchema类引入的SourceRecord是：
import org.apache.kafka.connect.source.SourceRecord;

Flink CDC 中引入的SourceRecord是
import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.source.SourceRecord;

我认为是Dinky代码中引入的不是shaded的类的原因

### How to reproduce

使用的官网案例
EXECUTE CDCSOURCE jobname WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '127.0.0.1',
  'port' = '3306',
  'username' = 'dlink',
  'password' = 'dlink',
  'checkpoint' = '3000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'test\.student,test\.score',
  'sink.connector'='datastream-kafka',
  'sink.topic'='dlinkcdc',
  'sink.brokers'='127.0.0.1:9092'
)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Dinky源码里改成shade依赖试试

**Comment by yuzq24** [comment]
> Dinky源码里改成shade依赖试试

在pom中修改依赖 
修改前：flink-connector-kafka 
修改后：flink-sql-connector-kafka
import位置使用：import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.source.SourceRecord; 
然后重新打包dinky-client-1.13，部署后解决该问题。

**Comment by aiwenmo** [comment]
> 

Good! Welcome to submit a PR.

**Comment by yuzq24** [comment]
> > 
> 
> Good! Welcome to submit a PR.

这种情况下，如果我修改成使用flink-sql-connector-kafka ，会不会造成其他flink集群中使用flink-connector-kafka的用户报相反的错呢？

**Comment by aiwenmo** [comment]
> > > 
> > 
> > 
> > Good! Welcome to submit a PR.
> 
> 这种情况下，如果我修改成使用flink-sql-connector-kafka ，会不会造成其他flink集群中使用flink-connector-kafka的用户报相反的错呢？

可以使用 ADD JAR 语法加载该依赖

**Comment by aiwenmo** [comment]
- [X] #1778
