### ISSUE TITLE
mysql 到 mysql 同步数据失败

### ISSUE THREAD

**Issue by ashuramojie** [DataLinkDC/dinky#1733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

create table source_t_sum (
 cnt int
)
WITH (
     'connector' = 'mysql-cdc'
    ,'hostname' = 'jdbc:mysql://chb1:3306/test'
    ,'port' = '3306'
    ,'username' = 'root'
    ,'password' = '123456'
    ,'server-time-zone' = 'UTC'
    ,'scan.incremental.snapshot.enabled' = 'true'
    ,'debezium.snapshot.mode'='latest-offset' 
    ,'debezium.datetime.format.timestamp.zone'='UTC+8'
    ,'database-name' = 'test'
    ,'table-name' = 't_sum'

);

CREATE TABLE sink_t_sum (
 cnt int
) WITH (
      'connector' = 'jdbc',
    'url' = 'jdbc:mysql://chb1:3306/flinktest',
    'table-name' = 't_sum',
    'username' = 'root',
    'password' = '123456' 
);

insert into sink_t_sum  select   * from source_t_sum ;

Caused by: org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction
ClassLoader info: URL ClassLoader:
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:336)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperator(OperatorChain.java:656)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:629)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:569)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:619)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:569)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:619)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:569)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:186)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeRestore(StreamTask.java:551)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:540)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:759)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.loadClass(FlinkUserCodeClassLoaders.java:172)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:76)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1984)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1848)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2158)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1665)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2403)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2327)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2185)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1665)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2403)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2327)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2185)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1665)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:501)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:459)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:615)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:600)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:587)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:541)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:322)
	... 14 more

因无法使用 connector  jdbc , 将 flink-connector-jdbc_2.12-1.13.5.jar , 放到 flink/lib 与 dlink / plugins下 之后,就报这个错了

### What you expected to happen

sink可以使用jdbc

### How to reproduce

create table source_t_sum (
 cnt int
)
WITH (
     'connector' = 'mysql-cdc'
    ,'hostname' = 'jdbc:mysql://chb1:3306/test'
    ,'port' = '3306'
    ,'username' = 'root'
    ,'password' = '123456'
    ,'server-time-zone' = 'UTC'
    ,'scan.incremental.snapshot.enabled' = 'true'
    ,'debezium.snapshot.mode'='latest-offset' 
    ,'debezium.datetime.format.timestamp.zone'='UTC+8'
    ,'database-name' = 'test'
    ,'table-name' = 't_sum'

);

CREATE TABLE sink_t_sum (
 cnt int
) WITH (
      'connector' = 'jdbc',
    'url' = 'jdbc:mysql://chb1:3306/flinktest',
    'table-name' = 't_sum',
    'username' = 'root',
    'password' = '123456' 
);

insert into sink_t_sum  select   * from source_t_sum ;

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
mysqlcdc 的参数 'hostname' 只填IP

**Comment by ashuramojie** [comment]
hostname更正之后是同样的报错

**Comment by aiwenmo** [comment]
怎么启动的dinky

**Comment by ashuramojie** [comment]
部署到服务器上 使用启动脚本start
其他的sink connector 是可以成功的

**Comment by aiwenmo** [comment]
> 部署到服务器上 使用启动脚本start 其他的sink connector 是可以成功的

具体的命令呢

**Comment by ashuramojie** [comment]
> > 部署到服务器上 使用启动脚本start 其他的sink connector 是可以成功的 
> 具体的命令呢
将 flink-connector-jdbc_2.12-1.13.5.jar , 放到 flink/lib 与 dlink / plugins下 之后
./auto.sh  restart  重启服务

**Comment by ashuramojie** [comment]
将 flink-connector-jdbc_2.12-1.13.5.jar , 放到 flink/lib 与 dlink / plugins下 之后
 ./auto.sh restart 重启服务
 在web 界面执行
create table source_t_sum (
cnt int
)
WITH (
'connector' = 'mysql-cdc'
,'hostname' = 'chb1'
,'port' = '3306'
,'username' = 'root'
,'password' = '123456'
,'server-time-zone' = 'UTC'
,'scan.incremental.snapshot.enabled' = 'true'
,'debezium.snapshot.mode'='latest-offset'
,'debezium.datetime.format.timestamp.zone'='UTC+8'
,'database-name' = 'test'
,'table-name' = 't_sum'

);

CREATE TABLE sink_t_sum (
cnt int
) WITH (
'connector' = 'jdbc',
'url' = 'jdbc:mysql://chb1:3306/flinktest',
'table-name' = 't_sum',
'username' = 'root',
'password' = '123456'
);

insert into sink_t_sum select * from source_t_sum ;

**Comment by ashuramojie** [comment]
> Cannot load user class: org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction
重启了flink dinky 之后同步成功了

**Comment by aiwenmo** [comment]
sh auto.sh start 1.13
