### ISSUE TITLE
[Bug] pg to hudi 数据类型转换错误

### ISSUE THREAD

**Issue by javaht** [DataLinkDC/dinky#1748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

pg数据到hudi 同步

java.lang.RuntimeException: java.lang.Integer cannot be cast to java.lang.Short
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.pushToRecordWriter(RecordWriterOutput.java:105) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.collect(RecordWriterOutput.java:89) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.collect(RecordWriterOutput.java:43) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:122) ~[dlink-client-1.14-0.7.2.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:108) ~[dlink-client-1.14-0.7.2.jar:?]
	at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:68) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.BroadcastingOutputCollector.collect(BroadcastingOutputCollector.java:84) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:62) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.ProcessOperator$ContextImpl.output(ProcessOperator.java:103) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:256) ~[dlink-client-1.14-0.7.2.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:243) ~[dlink-client-1.14-0.7.2.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:233) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:134) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:105) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:496) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:809) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:761) ~[flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) [flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937) [flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766) [flink-dist_2.12-1.14.5.jar:1.14.5]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575) [flink-dist_2.12-1.14.5.jar:1.14.5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

根据报错找到SqlSinkBuilder  发现是int2 类型 的问题 于是添加判断
else if (logicalType instanceof SmallIntType) {
			return   ((Integer) value).intValue();
		}
 之后打包上传重新跑任务，还是原来的错误。是我哪里修改的不对吗，或者说怎么修改？

### What you expected to happen

nothing

### How to reproduce

nothing

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by javaht** [comment]
按照群主的提示  修改了PostgreSqlTypeConvert中的判断。 把int2 对应到了int类型 这样写hudi不报错了

**Comment by javaht** [comment]
具体可以修改PostgreSqlTypeConvert的元数据映射

**Comment by aiwenmo** [comment]
欢迎 PR
