### ISSUE TITLE
flink on k8s 

### ISSUE THREAD

**Issue by fusonghe** [DataLinkDC/dinky#1757]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

  dlink writes flinksql running on k8s to find UDFs. org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function

### What you expected to happen

  dlink writes flinksql running on k8s to find UDFs. org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function

### How to reproduce

  dlink writes flinksql running on k8s to find UDFs. org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function

### Anything else

  dlink writes flinksql running on k8s to find UDFs. org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please provide more information. thx

**Comment by fusonghe** [comment]
org.apache.flink.runtime.JobException: Recovery is suppressed by FixedDelayRestartBackoffTimeStrategy(maxNumberRestartAttempts=10, backoffTimeMS=1000)
 at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138)
 at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82)
 at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:228)
 at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:218)
 at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:209)
 at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:679)
 at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:79)
 at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:444)
 at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:316)
 at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
 at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:314)
 at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217)
 at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78)
 at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163)
 at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
 at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
 at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
 at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
 at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
 at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
 at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
 at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
 at akka.actor.Actor.aroundReceive(Actor.scala:537)
 at akka.actor.Actor.aroundReceive$(Actor.scala:535)
 at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
 at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
 at akka.actor.ActorCell.invoke(ActorCell.scala:548)
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
 at akka.dispatch.Mailbox.run(Mailbox.scala:231)
 at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
 at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
 at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
 at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.
 at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:340)
 at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:155)
 at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.<init>(RegularOperatorChain.java:63)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:666)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:654)
 at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
 at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
 at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
 at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.StreamCorruptedException: unexpected block data
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1684)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2068)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1655)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2285)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
 at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:617)
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:602)
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:589)
 at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:543)
 at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:324)
 ... 9 more

**Comment by aiwenmo** [comment]
The StreamCorruptedException with the message "unexpected block data" is usually thrown when you try to read an object from an input stream that was not written properly or is corrupted.

When an object is serialized in Java, it is written as a sequence of bytes to an output stream. When you try to deserialize this object by reading from an input stream, the bytes are read and reconstructed into an object. If the byte sequence is not valid or has been corrupted, the deserialization process will fail and a StreamCorruptedException will be thrown.

To resolve this issue, you should investigate why the data in the input stream is corrupted. Possible causes could include network transmission errors, data corruption during storage, or a mismatch between the object's expected and actual class definition.

Here are a few suggestions to help you troubleshoot this issue:

1.Check if the data is being transmitted correctly over the network or if the file has been corrupted during storage.

2.Check if the serialization and deserialization processes are using the same serialization protocol. For example, check dinky plugins or flink lib.
