### ISSUE TITLE
[Bug] [metadata] Error in automatic table creation using CDCSOURCE,Mysql field unsigned type problem

### ISSUE THREAD

**Issue by Jrebel-i** [DataLinkDC/dinky#1787]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I use automatic table creation using mysql2mysql, an exception occurs if the source table field carries unsigned

### What you expected to happen

Successful table creation

## DDL：
CREATE TABLE `app_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT '' COMMENT '用户昵称',
  `email` varchar(50) NOT NULL COMMENT '用户邮箱',
  `phone` varchar(20) DEFAULT '' COMMENT '手机号',
  `gender` tinyint(4) unsigned DEFAULT '0' COMMENT '性别（0：男;1:女）',
  `password` varchar(100) NOT NULL COMMENT '密码',
  `age` tinyint(4) DEFAULT '0' COMMENT '年龄',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8 COMMENT='app用户表' 

## dlink.log：
[dlink] 2023-03-28 02:08:28 UTC INFO  com.dlink.metadata.driver.MySqlDriver 82 generateCreateTableSql - Auto generateCreateTableSql CREATE TABLE IF NOT EXISTS `sink_user_db`.`sink_app_user` (
  `id`  bigint unsigned(20) NOT  NULL  AUTO_INCREMENT ,
  `name`  varchar(50) DEFAULT "" COMMENT '用户昵称',
  `email`  varchar(50) NOT  NULL  COMMENT '用户邮箱',
  `phone`  varchar(20) DEFAULT "" COMMENT '手机号',
  `gender`  tinyint unsigned(4) DEFAULT 0 COMMENT '性别（0：男;1:女）',
  `password`  varchar(100) NOT  NULL  COMMENT '密码',
  `age`  tinyint(4) DEFAULT 0 COMMENT '年龄',
  `create_time`  datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time`  timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
 ENGINE=InnoDB COMMENT='app用户表';
[dlink] 2023-03-28 02:08:28 UTC ERROR com.dlink.trans.ddl.CreateCDCSourceOperation 203 build - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(20) NOT  NULL  AUTO_INCREMENT ,
  `name`  varchar(50) DEFAULT "" COMMENT '用' at line 2 java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(20) NOT  NULL  AUTO_INCREMENT ,
  `name`  varchar(50) DEFAULT "" COMMENT '用' at line 2
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:644) ~[druid-1.2.8.jar:1.2.8]
	at com.dlink.metadata.driver.AbstractJdbcDriver.execute(AbstractJdbcDriver.java:500) ~[dlink-metadata-base-0.7.2.jar:?]
	at com.dlink.metadata.driver.AbstractJdbcDriver.generateCreateTable(AbstractJdbcDriver.java:409) ~[dlink-metadata-base-0.7.2.jar:?]
	at com.dlink.trans.ddl.CreateCDCSourceOperation.checkAndCreateSinkTable(CreateCDCSourceOperation.java:228) ~[dlink-executor-0.7.2.jar:?]
	at

### Anything else

`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,         -->Source table
`id`  bigint unsigned(20) NOT  NULL  AUTO_INCREMENT ,     -->Auto generateCreateTableSql

### Version

0.7.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This is a bug.  I will fix it. thx
