### ISSUE TITLE
[Bug] [CDCSOURCE] oracle cdc整库同步到 iceberg 

### ISSUE THREAD

**Issue by czx-Adam** [DataLinkDC/dinky#1850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

2023-04-04 17:29:27,826 INFO  com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.json.JsonConverterConfig [] - JsonConverterConfig values: 
	converter.type = value
	decimal.format = BASE64
	schemas.cache.size = 1000
	schemas.enable = false

2023-04-04 17:29:29,209 ERROR com.dlink.cdc.AbstractSinkBuilder                            [] - SchameTable: TEMP.MB_AC_DATA_0001 - Row: {"before":null,"after":{"MS_ID":"987A272A2A8810AEE053152E12ACC944","INDEX_CODE":"ID0018803111","DATA_DATE":"2014-11-18","PUBLISH_TIME":1416328153000,"IS_DELETE":0,"UPDATE_TIME":1667466552000},"source":{"version":"1.5.4.Final","connector":"oracle","name":"oracle_logminer","ts_ms":1680600567322,"snapshot":"last","db":"GLYFDWH","sequence":null,"schema":"TEMP","table":"MB_AC_DATA_0001","txId":null,"scn":"1029463663","commit_scn":null,"lcr_position":null},"op":"r","ts_ms":1680600567330,"transaction":null} - Exception:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.dlink.cdc.sql.SQLSinkBuilder.convertValue(SQLSinkBuilder.java:302) ~[dlink-client-1.15-0.7.1.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:122) [dlink-client-1.15-0.7.1.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:110) [dlink-client-1.15-0.7.1.jar:?]
	at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:68) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.BroadcastingOutputCollector.collect(BroadcastingOutputCollector.java:84) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:62) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.ProcessOperator$ContextImpl.output(ProcessOperator.java:103) [flink-dist-1.15.3.jar:1.15.3]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:248) [dlink-client-1.15-0.7.1.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:238) [dlink-client-1.15-0.7.1.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103) [flink-dist-1.15.3.jar:1.15.3]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.emitRecordsUnderCheckpointLock(DebeziumChangeFetcher.java:252) [flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.handleBatch(DebeziumChangeFetcher.java:237) [flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.runFetchLoop(DebeziumChangeFetcher.java:151) [flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:446) [flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) [flink-dist-1.15.3.jar:1.15.3]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:332) [flink-dist-1.15.3.jar:1.15.3]

### What you expected to happen

CDCSOURCE

### How to reproduce

EXECUTE CDCSOURCE demo_print WITH (
  'connector'='oracle-cdc',
  'hostname'='127.0.0.1',
  'port'='1521',
  'username'='root',
  'password'='root',
  'checkpoint' = '10000',
  'database-name'='dm',
  'scan.startup.mode' = 'initial',
  'source.autoReconnect' = 'true',
  'parallelism' = '1',
  'table-name' = 'TEMP\.TABLE_0001,TEMP\.TABLE_0002',
  'sink.connector'='iceberg',
  'sink.table.lower'='true'
);

### Version

0.7.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
从日志里看下构建的目标表的 FlinkDDL

**Comment by czx-Adam** [comment]
CREATE TABLE IF NOT EXISTS `mb_ac_data_0001` (
    `MS_ID` STRING
    ,`INDEX_CODE` STRING
    ,`DATA_DATE` STRING
    ,`PUBLISH_TIME` TIMESTAMP
    ,`IS_DELETE` DECIMAL(1,0)
    ,`UPDATE_TIME` TIMESTAMP
    ,PRIMARY KEY ( `MS_ID` ) NOT ENFORCED
) WITH (
'connector' = 'iceberg'
)

**Comment by czx-Adam** [comment]
![图片](https://user-images.githubusercontent.com/22359459/230264756-c2712d02-b959-455b-84f1-1da164fb4618.png)
我这边定位到好像是这块强转有问题

**Comment by aiwenmo** [comment]
改成 String.valueOf 等方法试试

**Comment by czx-Adam** [comment]
嗯嗯，调整成String.valueOf 就没问题了

**Comment by aiwenmo** [comment]
欢迎提个PR修复下~
