### ISSUE TITLE
[Bug] flink1.16 mysqlcdc to hudi ，org.dinky.trans.ddl.ShowFragmentsOperation cannot be cast to org.dinky.trans.Operation

### ISSUE THREAD

**Issue by pual-wei** [DataLinkDC/dinky#1977]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: java.lang.ClassCastException: org.dinky.trans.ddl.ShowFragmentsOperation cannot be cast to org.dinky.trans.Operation
	at org.dinky.trans.Operations.lambda$getAllOperations$1(Operations.java:61) ~[dinky-app-1.16-0.8.0-jar-with-dependencies.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_321]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_321]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_321]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_321]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_321]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_321]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_321]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_321]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_321]
	at org.dinky.trans.Operations.getAllOperations(Operations.java:72) ~[dinky-app-1.16-0.8.0-jar-with-dependencies.jar:?]
	at org.dinky.trans.Operations.<clinit>(Operations.java:45) ~[dinky-app-1.16-0.8.0-jar-with-dependencies.jar:?]
	at org.dinky.app.flinksql.Submitter.submit(Submitter.java:214) ~[dinky-app-1.16-0.8.0-jar-with-dependencies.jar:?]
	at org.dinky.app.MainApp.main(MainApp.java:43) ~[dinky-app-1.16-0.8.0-jar-with-dependencies.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-dist-1.16.0.jar:1.16.0]
	... 12 more

### What you expected to happen

error

### How to reproduce

error

### Anything else

error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
use 0.7.4

**Comment by aiwenmo** [comment]
classloader.resolve-order: parent-first
https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/ops/debugging/debugging_classloading/#x-cannot-be-cast-to-x-exceptions
