### ISSUE TITLE
[Bug] No operators defined in streaming topology. Cannot execute.

### ISSUE THREAD

**Issue by pual-wei** [DataLinkDC/dinky#1982]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

2023-05-23 17:48:55,914 INFO  com.dlink.executor.Executor                                  [] - Simple authentication mode
2023-05-23 17:48:55,918 INFO  org.apache.flink.table.catalog.CatalogManager                [] - Set the current default catalog as [my_catalog] and the current default database as [default_database].
2023-05-23 17:48:55,918 INFO  com.dlink.app.flinksql.Submiter                              [] - 执行成功
2023-05-23 17:48:55,918 INFO  com.dlink.trans.AbstractOperation                            [] - Start build CDCSOURCE Task...
2023-05-23 17:48:56,339 ERROR com.alibaba.druid.stat.DruidDataSourceStatManager            [] - register mbean error
javax.management.MalformedObjectNameException: Invalid character '=' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618) ~[?:1.8.0_321]
	at javax.management.ObjectName.<init>(ObjectName.java:1382) ~[?:1.8.0_321]
	at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:162) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:2154) ~[druid-1.2.8.jar:1.2.8]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_321]
	at com.alibaba.druid.pool.DruidDataSource.registerMbean(DruidDataSource.java:2150) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:955) ~[druid-1.2.8.jar:1.2.8]
	at com.dlink.metadata.driver.AbstractJdbcDriver.createDataSource(AbstractJdbcDriver.java:107) ~[dlink-metadata-base-0.7.3.jar:?]
	at com.dlink.metadata.driver.AbstractJdbcDriver.setDriverConfig(AbstractJdbcDriver.java:119) ~[dlink-metadata-base-0.7.3.jar:?]
	at com.dlink.metadata.driver.Driver.get(Driver.java:51) ~[dlink-metadata-base-0.7.3.jar:?]
	at com.dlink.metadata.driver.Driver.buildNewConnection(Driver.java:70) ~[dlink-metadata-base-0.7.3.jar:?]
	at com.dlink.trans.ddl.CreateCDCSourceOperation.build(CreateCDCSourceOperation.java:138) ~[dlink-app.jar:?]
	at com.dlink.interceptor.FlinkInterceptor.build(FlinkInterceptor.java:54) ~[dlink-app.jar:?]
	at com.dlink.executor.Executor.pretreatExecute(Executor.java:230) ~[dlink-app.jar:?]
	at com.dlink.executor.Executor.executeSql(Executor.java:243) ~[dlink-app.jar:?]
	at com.dlink.app.flinksql.Submiter.submit(Submiter.java:226) ~[dlink-app.jar:?]
	at com.dlink.app.MainApp.main(MainApp.java:44) ~[dlink-app.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$2(ApplicationDispatcherBootstrap.java:254) ~[flink-clients-1.16.1.jar:1.16.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_321]
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_321]
2023-05-23 17:48:56,352 INFO  com.alibaba.druid.pool.DruidDataSource                       [] - {dataSource-1,jdbcmysql//127.0.0.13306/test_cdc?tinyInt1isBit=true} inited
2023-05-23 17:48:56,385 ERROR com.dlink.trans.AbstractOperation                            [] - com.dlink.model.Table cannot be cast to com.dlink.model.Table
java.lang.ClassCastException: com.dlink.model.Table cannot be cast to com.dlink.model.Table
	at com.dlink.trans.ddl.CreateCDCSourceOperation.build(CreateCDCSourceOperation.java:140) ~[dlink-app.jar:?]
	at com.dlink.interceptor.FlinkInterceptor.build(FlinkInterceptor.java:54) ~[dlink-app.jar:?]
	at com.dlink.executor.Executor.pretreatExecute(Executor.java:230) ~[dlink-app.jar:?]
	at com.dlink.executor.Executor.executeSql(Executor.java:243) ~[dlink-app.jar:?]
	at com.dlink.app.flinksql.Submiter.submit(Submiter.java:226) ~[dlink-app.jar:?]
	at com.dlink.app.MainApp.main(MainApp.java:44) ~[dlink-app.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$2(ApplicationDispatcherBootstrap.java:254) ~[flink-clients-1.16.1.jar:1.16.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_321]
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_321]
2023-05-23 17:48:56,388 INFO  com.dlink.app.flinksql.Submiter                              [] - 正在执行 FlinkSQL 语句集： EXECUTE CDCSOURCE demo_print WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '127.0.0.1',
  'port' = '3306',
  'username' = 'root',
  'password' = 'root',
  'checkpoint' = '10000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'test_cdc\.x_users',
  'sink.connector' = 'print'
)
2023-05-23 17:48:56,389 ERROR com.dlink.app.flinksql.Submiter                              [] - 执行失败, No operators defined in streaming topology. Cannot execute.
java.lang.IllegalStateException: No operators defined in streaming topology. Cannot execute.
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraphGenerator(StreamExecutionEnvironment.java:2272) ~[flink-streaming-java-1.16.1.jar:1.16.1]
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraph(StreamExecutionEnvironment.java:2239) ~[flink-streaming-java-1.16.1.jar:1.16.1]
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraph(StreamExecutionEnvironment.java:2230) ~[flink-streaming-java-1.16.1.jar:1.16.1]
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraph(StreamExecutionEnvironment.java:2216) ~[flink-streaming-java-1.16.1.jar:1.16.1]
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2043) ~[flink-streaming-java-1.16.1.jar:1.16.1]
	at com.dlink.executor.Executor.execute(Executor.java:234) ~[dlink-app.jar:?]
	at com.dlink.app.flinksql.Submiter.submit(Submiter.java:233) ~[dlink-app.jar:?]
	at com.dlink.app.MainApp.main(MainApp.java:44) ~[dlink-app.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-clients-1.16.1.jar:1.16.1]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$2(ApplicationDispatcherBootstrap.java:254) ~[flink-clients-1.16.1.jar:1.16.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_321]
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_407c4a71-f796-4832-9ce0-698ca7d2478a.jar:1.16.1]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [?:1.8.0_321]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_321]

### What you expected to happen

 EXECUTE CDCSOURCE demo_print WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '127.0.0.1',
  'port' = '3306',
  'username' = 'root',
  'password' = 'root',
  'checkpoint' = '10000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'test_cdc\.x_users',
  'sink.connector' = 'print'
)

### How to reproduce

![1684835923505](https://github.com/DataLinkDC/dinky/assets/104356714/2c6851b3-8e46-486e-8d9c-f3c063dabd06)

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please try the yarn-session mode first.

**Comment by aiwenmo** [comment]
classloader.resolve-order: parent-first
https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/ops/debugging/debugging_classloading/#x-cannot-be-cast-to-x-exceptions
