### ISSUE TITLE
[Bug] [dinky-admin] Could not create Kubernetes cluster 

### ISSUE THREAD

**Issue by kevinlin299** [DataLinkDC/dinky#2003]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

After packaging and deployment using dinky 0.7.0 source code，When adding flink to Kubernetes Native to start the cluster, an error is reported
`[dlink] 2023-06-01 16:17:03 CST INFO  com.dlink.gateway.kubernetes.KubernetesGateway 220 test - 配置连接测试成功
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.rpc.address, localhost
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.rpc.port, 6123
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.memory.process.size, 1600m
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.memory.process.size, 1728m
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.numberOfTaskSlots, 1
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: parallelism.default, 1
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.interval, 5000
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.checkpoints.num-retained, 20
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.mode, EXACTLY_ONCE
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.externalized-checkpoint-retention, RETAIN_ON_CANCELLATION
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.backend, rocksdb
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.checkpoints.dir, s3:///flink-checkpoints
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.savepoints.dir, s3:///flink-savepoints
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: s3.access-key, flink
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: s3.secret-key, ******
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: s3.endpoint, http://127.0.1.0:9000
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: fs.s3.path.style.access, true
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.execution.failover-strategy, region
[dlink] 2023-06-01 16:17:08 CST INFO  com.dlink.gateway.kubernetes.FlinkKubeClientFactory 70 fromConfiguration - Configuring kubernetes client to use context yunfeng-api.
[dlink] 2023-06-01 16:17:08 CST INFO  com.dlink.gateway.kubernetes.FlinkKubeClientFactory 72 fromConfiguration - Configuring kubernetes client to use context yunfeng-api.
[dlink] 2023-06-01 16:17:08 CST INFO  com.dlink.gateway.kubernetes.FlinkKubeClientFactory 75 fromConfiguration - kube file:/root/.kube/config
[dlink] 2023-06-01 16:17:08 CST INFO  com.dlink.gateway.kubernetes.FlinkKubeClientFactory 78 fromConfiguration - Trying to load kubernetes config from file: /root/.kube/config.
[dlink] 2023-06-01 16:17:08 CST INFO  com.dlink.gateway.kubernetes.FlinkKubeClientFactory 111 fromConfiguration - client:io.fabric8.kubernetes.client.DefaultKubernetesClient@27010f68
[dlink] 2023-06-01 16:17:08 CST INFO  com.dlink.gateway.kubernetes.KubernetesGateway 107 initKubeClient - kubeClient:org.apache.flink.kubernetes.kubeclient.Fabric8FlinkKubeClient@527dee5d
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.rpc.address, localhost
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.rpc.port, 6123
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.memory.process.size, 1600m
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.memory.process.size, 1728m
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.numberOfTaskSlots, 1
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: parallelism.default, 1
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.interval, 5000
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.checkpoints.num-retained, 20
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.mode, EXACTLY_ONCE
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.externalized-checkpoint-retention, RETAIN_ON_CANCELLATION
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.backend, rocksdb
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.checkpoints.dir, s3:///flink-checkpoints
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.savepoints.dir, s3:///flink-savepoints
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: s3.access-key, flink
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: s3.secret-key, ******
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: s3.endpoint, http://127.0.01:9000
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: fs.s3.path.style.access, true
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.execution.failover-strategy, region
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.kubernetes.utils.KubernetesUtils 100 checkAndUpdatePortConfigOption - Kubernetes deployment requires a fixed port. Configuration blob.server.port will be set to 6124
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.kubernetes.utils.KubernetesUtils 100 checkAndUpdatePortConfigOption - Kubernetes deployment requires a fixed port. Configuration taskmanager.rpc.port will be set to 6122
[dlink] 2023-06-01 16:17:08 CST INFO  org.apache.flink.configuration.Configuration 804 loggingFallback - Config uses fallback configuration key 'kubernetes.pod-template-file' instead of key 'kubernetes.pod-template-file.jobmanager'
[dlink] 2023-06-01 16:17:08 CST WARN  org.apache.flink.kubernetes.KubernetesClusterDescriptor 279 deployClusterInternal - Failed to create the Kubernetes cluster "session001", try to clean up the residual resources.
[dlink] 2023-06-01 16:17:08 CST ERROR com.dlink.utils.LogUtil 46 getError - org.apache.flink.client.deployment.ClusterDeploymentException: Could not create Kubernetes cluster "session001".
        at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployClusterInternal(KubernetesClusterDescriptor.java:289)
        at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deploySessionCluster(KubernetesClusterDescriptor.java:158)
        at com.dlink.gateway.kubernetes.KubernetesSessionGateway.deployCluster(KubernetesSessionGateway.java:92)
        at com.dlink.job.JobManager.deploySessionCluster(JobManager.java:716)
        at com.dlink.service.impl.ClusterServiceImpl.deploySessionCluster(ClusterServiceImpl.java:178)
        at com.dlink.service.impl.ClusterServiceImpl$$FastClassBySpringCGLIB$$d1f6e853.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at com.dlink.service.impl.ClusterServiceImpl$$EnhancerBySpringCGLIB$$89ad84b.deploySessionCluster(<generated>)
        at com.dlink.controller.ClusterController.deploySessionCluster(ClusterController.java:197)
        at com.dlink.controller.ClusterController$$FastClassBySpringCGLIB$$e7b26861.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.dlink.controller.ClusterController$$EnhancerBySpringCGLIB$$13eef556.deploySessionCluster(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:670)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at org.apache.flink.configuration.ConfigurationUtils.convertToString(ConfigurationUtils.java:388)
        at org.apache.flink.configuration.ConfigurationUtils.lambda$convertToString$11(ConfigurationUtils.java:396)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.apache.flink.configuration.ConfigurationUtils.convertToString(ConfigurationUtils.java:397)
        at org.apache.flink.configuration.Configuration.toMap(Configuration.java:720)
        at org.apache.flink.configuration.ConfigurationUtils.getPrefixedKeyValuePairs(ConfigurationUtils.java:268)
        at org.apache.flink.kubernetes.kubeclient.parameters.KubernetesJobManagerParameters.getEnvironments(KubernetesJobManagerParameters.java:83)
        at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.getCustomizedEnvs(InitJobManagerDecorator.java:174)
        at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateMainContainer(InitJobManagerDecorator.java:145)
        at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateFlinkPod(InitJobManagerDecorator.java:100)
        at org.apache.flink.kubernetes.kubeclient.factory.KubernetesJobManagerFactory.buildKubernetesJobManagerSpecification(KubernetesJobManagerFactory.java:79)
        at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployClusterInternal(KubernetesClusterDescriptor.java:271)
        ... 77 more

[dlink] 2023-06-01 16:17:08 CST ERROR com.dlink.exception.WebExceptionHandler 97 unknownException - ERROR: java.lang.NullPointerException: null
        at com.dlink.service.impl.ClusterServiceImpl.deploySessionCluster(ClusterServiceImpl.java:180) ~[dlink-admin-0.7.0.jar:?]
        at com.dlink.service.impl.ClusterServiceImpl$$FastClassBySpringCGLIB$$d1f6e853.invoke(<generated>) ~[dlink-admin-0.7.0.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.23.jar:5.3.23]
        at com.dlink.service.impl.ClusterServiceImpl$$EnhancerBySpringCGLIB$$89ad84b.deploySessionCluster(<generated>) ~[dlink-admin-0.7.0.jar:?]
        at com.dlink.controller.ClusterController.deploySessionCluster(ClusterController.java:197) ~[dlink-admin-0.7.0.jar:?]
        at com.dlink.controller.ClusterController$$FastClassBySpringCGLIB$$e7b26861.invoke(<generated>) ~[dlink-admin-0.7.0.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.23.jar:5.3.23]
        at com.dlink.controller.ClusterController$$EnhancerBySpringCGLIB$$13eef556.deploySessionCluster(<generated>) ~[dlink-admin-0.7.0.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[tomcat-embed-core-9.0.68.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.68.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124) ~[druid-1.2.8.jar:1.2.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar:5.3.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar:5.3.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar:5.3.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]`

### What you expected to happen

user flink on kubernetes native，but the cluster configuration in both modes is unsuccessful, so please give the configuration document

### How to reproduce

Clone the dinky source code in the git repository, switch to 0.7.0 tag, and package it with flink1.13, java11, web, prod, fast, scala-2.12 profile

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Upgrade into 0.7.3
