### ISSUE TITLE
previously initiated loading for a different type with name "com/mysql/cj/Session"

### ISSUE THREAD

**Issue by xuanzhi201111** [DataLinkDC/dinky#2117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我的flink是1.13.6，然后启动的时候sh auto.sh start 1.13 ，然后
ll plugins/flink1.13/dinky/
total 258512
-rwxrwxrwx 1 root    root        21552 Apr 19 22:08 dlink-catalog-mysql-1.13-0.7.3.jar
-rwxrwxrwx 1 root    root       136617 Apr 19 22:08 dlink-client-1.13-0.7.3.jar
-rwxrwxrwx 1 root    root        48459 Apr 19 22:10 dlink-connector-jdbc-1.13-0.7.3.jar_bak
-rw-r--r-- 1 root    root      4587415 Mar 31  2022 flink-connector-clickhouse-1.14.3-SNAPSHOT.jar
-rw-r--r-- 1 root    root       249570 May 24  2022 flink-connector-jdbc_2.11-1.13.6.jar
-rw-r--r-- 1 ygpjump ygpops2     92314 Feb  4  2022 flink-csv-1.13.6.jar
-rw-r--r-- 1 ygpjump ygpops2 115425612 Feb  4  2022 flink-dist_2.11-1.13.6.jar
-rwxr-xr-x 1 root    root       148127 Mar  9  2022 flink-json-1.13.6.jar
-rw-r--r-- 1 ygpjump ygpops2   7709740 May  7  2021 flink-shaded-zookeeper-3.4.14.jar
-rw-r--r-- 1 root    root       523448 May 24  2022 flink-sql-client_2.11-1.13.6.jar
-rw-r--r-- 1 root    root     27764265 May 24  2022 flink-sql-connector-elasticsearch7_2.11-1.13.6.jar
-rw-r--r-- 1 root    root      3674190 Jun 21  2022 flink-sql-connector-kafka_2.11-1.13.6.jar
-rw-r--r-- 1 root    root     22096298 Aug 29  2022 flink-sql-connector-mysql-cdc-2.2.1.jar
-rw-r--r-- 1 root    root         7086 Mar  9  2022 flink-sql-json-1.0.jar
-rw-r--r-- 1 ygpjump ygpops2  36455408 Feb  4  2022 flink-table_2.11-1.13.6.jar
-rw-r--r-- 1 ygpjump ygpops2  41077430 Feb  4  2022 flink-table-blink_2.11-1.13.6.jar
-rw-r--r-- 1 ygpjump ygpops2    208006 Jan 13  2022 log4j-1.2-api-2.17.1.jar
-rw-r--r-- 1 ygpjump ygpops2    301872 Jan  7  2022 log4j-api-2.17.1.jar
-rw-r--r-- 1 ygpjump ygpops2   1790452 Jan  7  2022 log4j-core-2.17.1.jar
-rw-r--r-- 1 ygpjump ygpops2     24279 Jan  7  2022 log4j-slf4j-impl-2.17.1.jar
-rwxr-xr-x 1 root    root      2293144 Mar  9  2022 mysql-connector-java-8.0.16.jar

运行job的时候会报 ：
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "com/mysql/cj/Session"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.ververica.cdc.connectors.shaded.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.ververica.cdc.connectors.mysql.source.connection.PooledDataSourceFactory.createPooledDataSource(PooledDataSourceFactory.java:63)
	at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionPools.getOrCreateConnectionPool(JdbcConnectionPools.java:51)
	at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:53)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:872)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:867)
	at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:413)
	at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:62)
	at com.ververica.cdc.connectors.mysql.MySqlValidator.validate(MySqlValidator.java:68)
	at com.ververica.cdc.connectors.mysql.source.MySqlSource.createEnumerator(MySqlSource.java:174)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:129)

### What you expected to happen

远程

### How to reproduce

无

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xuanzhi201111** [comment]
作者，这个怎么解决呢

**Comment by aiwenmo** [comment]
Remove flink-sql-connector-mysql-cdc-2.2.1.jar.
