### ISSUE TITLE
[Bug]写数据到hive报错

### ISSUE THREAD

**Issue by Flutemr** [DataLinkDC/dinky#2203]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我测试从kafka写数据到hive。里面使用了udf函数，是使用fix代码后，自己编译的。flinksql如下：
SET 'execution.checkpointing.interval' = '10s';
CREATE CATALOG myhive WITH (
    'type' = 'hive',
    'default-database' = 'test',
    'hive-conf-dir' = '/opt/module/hive-3.1.3/conf'
);
-- set the HiveCatalog as the current catalog of the session
USE CATALOG myhive;
--创建kafka的虚拟表
create temporary table app_log_kafka(
   tags string comment'标签',
   `event` row<original string> comment '事件',
   `service` string comment '服务',
   `log`  row<`file` row<`path` string>> comment '日志',
   `@version` string comment '版本',
   `host` row<id string,mac string,`ip` string,hostname string,architecture string,
        os row<`name` string,`type` string,codename string,platform string,
        `version` string,family string,kernel string>,containerized string>  comment '主机',
   `message` string comment '信息',
   `@timestamp` string comment '时间戳'
)with(
  'connector' = 'kafka',
  'topic' = 'application-log',
  'properties.bootstrap.servers' = 'localhost:9092',
  'properties.group.id' = 'test_consumer_group',
  -- 'scan.startup.mode' = 'earliest-offset',
  'scan.startup.mode' = 'latest-offset',
  'value.format' = 'json'
);
create temporary function tpipv4 as 'com.yyt.TQIPV4';
create temporary function dateformatzdy as 'com.yyt.DateFormats';

--写入hive
insert into  test.test_zdg_log_pr
/*+
OPTIONS(
    -- 'sink.rolling-policy.file-size' = '100KB',
    -- 'sink.rolling-policy.rollover-interval'='1 minute',
    -- 'sink.rolling-policy.check-interval'='1 minute',
    -- 设置分区提交触发器为分区时间
    'sink.partition-commit.trigger' = 'process-time',
    -- 设置分区提交延迟时间，这儿设置 1 分钟，是因为分区时间为 1 分钟间隔
    'sink.partition-commit.delay' = '0s',
    -- 设置水印时区
    'sink.partition-commit.watermark-time-zone' = 'GMT+08:00',
    -- 设置分区提交策略，这儿是将分区提交到元数据存储，并且在分区目录下生成 success 文件
    'sink.partition-commit.policy.kind' = 'metastore,success-file',
    -- sink 并行度
    'sink.parallelism' = '1'
)
 */
select 
  id,
  `ip`,
  hostname,
  `service`,
 cast(`time` as string) as `time`,
  `level`,
  mac,
  os,
  arch,
  filepath,
  thread,
  `method`,
  `content`,
  date_format(`time`, 'yyyyMMddHHmm') as mi
from(
  select
  cast(UUID() as STRING)  as id,
  tpipv4(host.`ip`) as `ip`,
  host.hostname as hostname,
  `service`,
  case when `service` = 'accserver_zaxq_rtmpProxy265' 
       then  cast(dateformatzdy(concat_ws('',substr(SPLIT_INDEX(`log`.`file`.`path`,'\\\',3),1,8),REGEXP_EXTRACT(`message`,'\s+(\d{1,2}:\d{1,2}:\d{1,2})\:',1))) as TIMESTAMP)
       when `service` in ('poi-server_zaxq_tag-api','dbview_zaxq_STKServerNew','media2_zaxq_STKServer','media_zaxq_search','servicegw_zaxq_poi-api','poi-server_zaxq_firectrl-api','accserver_zaxq_zacms') 
       then  cast(REGEXP_EXTRACT(`message`,'.*(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*',1) as TIMESTAMP)
       else cast(REGEXP_EXTRACT(`message`,'.*(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*',1) as TIMESTAMP) end as `time`,
  cast('INFO' as STRING) as `level`,
  cast('aa-dd-cc' AS STRING) as mac,
  cast('OS' AS STRING) as os,
  cast('wz' AS STRING) as arch,
  `log`.`file`.`path` as filepath,
  cast('11' AS STRING) as thread,
  cast('fs' AS STRING) as `method`,
  cast('aaaaaaa' AS STRING) as `content`
from app_log_kafka
)t1
where `time` is not null;

先在local模式下运行，报错如下：

2023-08-12T14:28:58.567: Exception in executing FlinkSQL:
insert into  test.test_zdg_log_pr
/*+
OPTIONS(
    'sink.partition-commit.trigger' = 'process-time'  ,
    'sink.partition-commit.delay' = '0s',
    'sink.partition-commit.watermark-time-zone' = 'GMT+08:00',
    'sink.partition-commit.policy.kind' = 'metastore,success-file',
    'sink.parallelism' = '1'
)
 */
select 
  id,
  `ip`,
  hostname,
  `service`,
 cast(`time` as string) as `time`,
  `level`,
  mac,
  os,
  arch,
  filepath,
  thread,
  `method`,
  `content`,
  date_format(`time`, 'yyyyMMddHHmm') as mi
from(
  select
  cast(UUID() as STRING)  as id,
  tpipv4(host.`ip`) as `ip`,
  host.hostname as hostname,
  `service`,
  case when `service` = 'accserver_zaxq_rtmpProxy265' 
       then  cast(dateformatzdy(concat_ws('',substr(SPLIT_INDEX(`log`.`file`.`path`,'\\\',3),1,8),REGEXP_EXTRACT(`message`,'\s+(\d{1,2}:\d{1,2}:\d{1,2})\:',1))) as TIMESTAMP)
       when `service` in ('poi-server_zaxq_tag-api','dbview_zaxq_STKServerNew','media2_zaxq_STKServer','media_zaxq_search','servicegw_zaxq_poi-api','poi-server_zaxq_firectrl-api','accserver_zaxq_zacms') 
       then  cast(REGEXP_EXTRACT(`message`,'.*(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*',1) as TIMESTAMP)
       else cast(REGEXP_EXTRACT(`message`,'.*(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*',1) as TIMESTAMP) end as `time`,
  cast('INFO' as STRING) as `level`,
  cast('aa-dd-cc' AS STRING) as mac,
  cast('OS' AS STRING) as os,
  cast('wz' AS STRING) as arch,
  `log`.`file`.`path` as filepath,
  cast('11' AS STRING) as thread,
  cast('fs' AS STRING) as `method`,
  cast('aaaaaaa' AS STRING) as `content`
from app_log_kafka
)t1
where `time` is not null 
Error message:
 org.apache.flink.table.api.TableException: Failed to execute sql
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:867)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:827)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:918)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:730)
	at com.dlink.executor.Executor.executeSql(Executor.java:249)
	at com.dlink.job.JobManager.executeSql(JobManager.java:512)
	at com.dlink.service.impl.StudioServiceImpl.executeFlinkSql(StudioServiceImpl.java:202)
	at com.dlink.service.impl.StudioServiceImpl.executeSql(StudioServiceImpl.java:189)
	at com.dlink.service.impl.StudioServiceImpl$$FastClassBySpringCGLIB$$e3eb787.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.dlink.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:65)
	at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.dlink.service.impl.StudioServiceImpl$$EnhancerBySpringCGLIB$$5421b6ea.executeSql(<generated>)
	at com.dlink.controller.StudioController.executeSql(StudioController.java:78)
	at com.dlink.controller.StudioController$$FastClassBySpringCGLIB$$e6483d87.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.dlink.controller.StudioController$$EnhancerBySpringCGLIB$$80366810.executeSql(<generated>)
	at sun.reflect.GeneratedMethodAccessor554.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:696)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.util.FlinkRuntimeException: org.apache.flink.api.common.InvalidProgramException: Table program cannot be compiled. This is a bug. Please file an issue.
	at org.apache.flink.table.runtime.generated.CompileUtils.compile(CompileUtils.java:94)
	at org.apache.flink.table.runtime.generated.GeneratedClass.compile(GeneratedClass.java:101)
	at org.apache.flink.table.runtime.generated.GeneratedClass.getClass(GeneratedClass.java:120)
	at org.apache.flink.table.runtime.operators.CodeGenOperatorFactory.getStreamOperatorClass(CodeGenOperatorFactory.java:51)
	at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.preValidate(StreamingJobGraphGenerator.java:498)
	at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobGraph(StreamingJobGraphGenerator.java:221)
	at org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator.createJobGraph(StreamingJobGraphGenerator.java:153)
	at org.apache.flink.streaming.api.graph.StreamGraph.getJobGraph(StreamGraph.java:1024)
	at org.apache.flink.client.StreamGraphTranslator.translateToJobGraph(StreamGraphTranslator.java:56)
	at org.apache.flink.client.FlinkPipelineTranslationUtil.getJobGraph(FlinkPipelineTranslationUtil.java:43)
	at org.apache.flink.client.deployment.executors.PipelineExecutorUtils.getJobGraph(PipelineExecutorUtils.java:59)
	at org.apache.flink.client.deployment.executors.LocalExecutor.getJobGraph(LocalExecutor.java:105)
	at org.apache.flink.client.deployment.executors.LocalExecutor.execute(LocalExecutor.java:82)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:2188)
	at org.apache.flink.table.planner.delegation.DefaultExecutor.executeAsync(DefaultExecutor.java:95)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:850)
	... 93 more
Caused by: org.apache.flink.shaded.guava30.com.google.common.util.concurrent.UncheckedExecutionException: org.apache.flink.api.common.InvalidProgramException: Table program cannot be compiled. This is a bug. Please file an issue.
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4859)
	at org.apache.flink.table.runtime.generated.CompileUtils.compile(CompileUtils.java:92)
	... 108 more
Caused by: org.apache.flink.api.common.InvalidProgramException: Table program cannot be compiled. This is a bug. Please file an issue.
	at org.apache.flink.table.runtime.generated.CompileUtils.doCompile(CompileUtils.java:107)
	at org.apache.flink.table.runtime.generated.CompileUtils.lambda$compile$0(CompileUtils.java:92)
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4864)
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at org.apache.flink.shaded.guava30.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 111 more
Caused by: org.codehaus.commons.compiler.CompileException: Line 20, Column 30: Cannot determine simple type name "com"
	at org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:12211)
	at org.codehaus.janino.UnitCompiler.getReferenceType(UnitCompiler.java:6833)
	at org.codehaus.janino.UnitCompiler.getReferenceType(UnitCompiler.java:6594)
	at org.codehaus.janino.UnitCompiler.getReferenceType(UnitCompiler.java:6607)
	at org.codehaus.janino.UnitCompiler.getReferenceType(UnitCompiler.java:6607)
	at org.codehaus.janino.UnitCompiler.getType2(UnitCompiler.java:6573)
	at org.codehaus.janino.UnitCompiler.access$13900(UnitCompiler.java:215)
	at org.codehaus.janino.UnitCompiler$22$1.visitReferenceType(UnitCompiler.java:6481)
	

### What you expected to happen

这个是因为修改源码，让udf可以用的原因吗？

### How to reproduce

无

### Anything else

使用的是flink1.16   dinky0.7.3  hive3.1.3

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please use exclusion method to verify the problem.

**Comment by Flutemr** [comment]
> Please use exclusion method to verify the problem.

好的，如果我注释了udf，它是可以运行的；如果我加上udf，它就报这个错误。我怀疑是修复的udf的那个代码有些兼容问题。我是按照下面这issues修复代码后编译的:
https://github.com/DataLinkDC/dinky/pull/1581。
下面是我在dinky用模板写的udf。
![1691974352632](https://github.com/DataLinkDC/dinky/assets/30035663/cde17bd7-b025-4f8f-b4ab-7596df9b5a20)

**Comment by flhst** [comment]
你好我想问下解决了吗，我也遇到了这个问题。

**Comment by wandayou** [comment]
你好我想问下解决了吗，我也遇到了这个问题。

**Comment by Flutemr** [comment]
> 你好我想问下解决了吗，我也遇到了这个问题。

就是兼容问题，你用最新的dinky版本看看

**Comment by wandayou** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。谢谢！
                                                              ---万大友

**Comment by wandayou** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。谢谢！
                                                              ---万大友
