### ISSUE TITLE
[Bug] [mysqlcdc] [starrocks] DruidDataSourceStatManager bug and starrocks no auto migratioin 

### ISSUE THREAD

**Issue by yylyhy** [DataLinkDC/dinky#2328]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky version 0.7.4
使用文档中整库同步mysqlcdc->starrocks例子

报错如下：
[dlink] 2023-09-18 21:07:17 CST ERROR com.alibaba.druid.stat.DruidDataSourceStatManager 165 addDataSource - register mbean error javax.management.MalformedObjectNameException: Invalid character '=' in value part of property
[dlink] 2023-09-18 21:07:18 CST INFO  com.dlink.cdc.sql.SQLSinkBuilder 216 addSinkInsert - Create ods_dl_ambassador_user FlinkSQL insert into successful...
[dlink] 2023-09-18 21:07:25 CST ERROR com.dlink.trans.ddl.CreateCDCSourceOperation 200 build - Failed to get table schema info from StarRocks. StarRocks process failed java.lang.IllegalArgumentException: Failed to get table schema info from StarRocks. StarRocks process failed
	at com.starrocks.connector.flink.manager.StarRocksQueryVisitor.getTableColumnsMetaData(StarRocksQueryVisitor.java:60) ~[flink-connector-starrocks-1.2.3_flink-1.14_2.11.jar:?]
	at com.starrocks.connector.flink.manager.StarRocksSinkManager.validateTableStructure(StarRocksSinkManager.java:401) ~[flink-connector-starrocks-1.2.3_flink-1.14_2.11.jar:?]
	at com.starrocks.connector.flink.manager.StarRocksSinkManager.init(StarRocksSinkManager.java:128) ~[flink-connector-starrocks-1.2.3_flink-1.14_2.11.jar:?]
	at com.starrocks.connector.flink.manager.StarRocksSinkManager.<init>(StarRocksSinkManager.java:123) ~[flink-connector-starrocks-1.2.3_flink-1.14_2.11.jar:?]
	at com.starrocks.connector.flink.table.sink.StarRocksDynamicSinkFunction.<init>(StarRocksDynamicSinkFunction.java:73) ~[flink-connector-starrocks-1.2.3_flink-1.14_2.11.jar:?]
	at com.starrocks.connector.flink.table.sink.StarRocksDynamicTableSink.getSinkRuntimeProvider(StarRocksDynamicTableSink.java:45) ~[flink-connector-starrocks-1.2.3_flink-1.14_2.11.jar:?]
	at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecSink.createSinkTransformation(CommonExecSink.java:121) ~[flink-table_2.11-1.14.0.jar:1.14.0]
	at org.apache.flink.table.planner.plan.nodes.exec.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.java:140) ~[flink-table_2.11-1.14.0.jar:1.14.0]
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:134) ~[flink-table_2.11-1.14.0.jar:1.14.0]
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$1.apply(StreamPlanner.scala:71) ~[flink-table_2.11-1.14.0.jar:1.14.0]
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$1.apply(StreamPlanner.scala:70) ~[flink-table_2.11-1.14.0.jar:1.14.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[flink-dist_2.11-1.14.0.jar:1.14.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[flink-dist_2.11-1.14.0.jar:1.14.0]

### What you expected to happen

整库整表自动同步

### How to reproduce

dinky version 0.7.4
flink version 1.14
starrocks connect 1.2.3

EXECUTE CDCSOURCE s123433 WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'xxx',
  'port' = '3306',
  'username' = 'dinky',
  'password' = 'xxxx',
  'checkpoint' = '3000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'delundb\.xxxx',
  'sink.connector' = 'starrocks',
  'sink.jdbc-url' = 'jdbc:mysql://172.16.9.165:19030?connectionTimeZone=Asia/Shanghai',
  'sink.load-url' = '172.16.9.165:18030',
  'sink.username' = 'root',
  'sink.password' = '',
  'sink.sink.db' = 'ods',
  'sink.table.prefix' = 'ods_',
  'sink.table.lower' = 'true',
  'sink.database-name' = 'ods',
  'sink.table-name' = '${tableName}',
  'sink.sink.properties.format' = 'json',
  'sink.sink.properties.strip_outer_array' = 'true',
  'sink.sink.max-retries' = '10',
  'sink.sink.buffer-flush.interval-ms' = '15000',
  'sink.sink.parallelism' = '1'
)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Check if the jobgraph has successfully constructed the sink operator.
