### ISSUE TITLE
[Bug] [dlink-client] Oracle entire database synchronization failed

### ISSUE THREAD

**Issue by kevinlin299** [DataLinkDC/dinky#2413]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

first，Thank you for the excellent project, big brother.
I used flink1.13.6 and dinky0.7.4 to create a full-database synchronization task for Oracle, and the instance runs normally, but the log shows that the conversion of LinkHashMap in dlink-client module failed, with the specific error message:

2023-10-20 17:36:31,179 ERROR com.dlink.cdc.AbstractSinkBuilder                            [] - SchameTable: DC.REPORT_INFO - Row: {"before":null,"after":{"ID":{"scale":0,"value":"CQ=="},"NAME":"11","SORT_NAME":"????????????????????????","URL":""},"source":{"version":"1.6.4.Final","connector":"oracle","name":"oracle_logminer","ts_ms":1697794590090,"snapshot":"true","db":"ORCL","sequence":null,"schema":"DATA","table":"INFO","txId":null,"scn":"102781299509","commit_scn":null,"lcr_position":null},"op":"r","ts_ms":1697794590091,"transaction":null} - Exception:
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
	at com.dlink.cdc.sql.SQLSinkBuilder.convertValue(SQLSinkBuilder.java:340) ~[blob_p-a95981346692fbd3add23098e385dc3052d68ec8-6acffca9653e8439e6f9be962d2565bf:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:122) [blob_p-a95981346692fbd3add23098e385dc3052d68ec8-6acffca9653e8439e6f9be962d2565bf:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:110) [blob_p-a95981346692fbd3add23098e385dc3052d68ec8-6acffca9653e8439e6f9be962d2565bf:?]
	at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.ProcessOperator$ContextImpl.output(ProcessOperator.java:103) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:285) [blob_p-a95981346692fbd3add23098e385dc3052d68ec8-6acffca9653e8439e6f9be962d2565bf:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:275) [blob_p-a95981346692fbd3add23098e385dc3052d68ec8-6acffca9653e8439e6f9be962d2565bf:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:317) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:411) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.emitRecordsUnderCheckpointLock(DebeziumChangeFetcher.java:259) [blob_p-57d4e08f845757db1ec7d6ebe5e1158c3b8e466f-8c82dfb2381dc379c468c636020f77c7:2.3.0]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.handleBatch(DebeziumChangeFetcher.java:244) [blob_p-57d4e08f845757db1ec7d6ebe5e1158c3b8e466f-8c82dfb2381dc379c468c636020f77c7:2.3.0]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.runFetchLoop(DebeziumChangeFetcher.java:150) [blob_p-57d4e08f845757db1ec7d6ebe5e1158c3b8e466f-8c82dfb2381dc379c468c636020f77c7:2.3.0]
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:444) [blob_p-57d4e08f845757db1ec7d6ebe5e1158c3b8e466f-8c82dfb2381dc379c468c636020f77c7:2.3.0]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:104) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:60) [flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269) [flink-dist_2.12-1.13.6.jar:1.13.6]

### What you expected to happen

use the Oracle synchronization feature normally

### How to reproduce

used flink1.13.6 and dinky0.7.4 to create a full-database synchronization task for Oracle,my code like this
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/dlink-client-1.13-0.7.4.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/dlink-client-base-0.7.4.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/HikariCP-4.0.3.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/druid-1.2.8.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/dlink-metadata-oracle-0.7.4.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/dlink-metadata-base-0.7.4.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/flink-shaded-guava-18.0-13.0.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/jackson-datatype-jsr310-2.13.4.jar';
add jar '/opt/dinky/dlink-release-0.7.4/dlink-doc/cdc-source/flink-sql-connector-oracle-cdc-2.3.0.jar';

EXECUTE CDCSOURCE cdc_oracle WITH (
 'connector' = 'oracle-cdc',
 'hostname' = '192.168.1.1',
 'port' = '1521',
 'username'='root',
 'password'='123456',
 'database-name'='ORCL',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'table-name' = 'DATA\.INFO',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:oracle:thin:@192.168.1.2:1521:ORCL',
 'sink.username' = 'root',
 'sink.password' = '111111',
 'sink.table-name' = 'DATA1.${tableName}',
 'sink.driver' = 'oracle.jdbc.driver.OracleDriver'

the job picture
![image](https://github.com/DataLinkDC/dinky/assets/40079776/e4fc68b9-ea3f-4ae2-a59a-17dcf2c94405)
the log
![image](https://github.com/DataLinkDC/dinky/assets/40079776/5c472a71-e7ce-4f7f-8a0d-ef00dccd45ab)

### Anything else

when i try to fix this problem in the source code(module dlink-client class:com.dlink.cdc.AbstractSinkBuilder),but it not work, job have a cdcBuilder task,not have sinkBuilder task.

![image](https://github.com/DataLinkDC/dinky/assets/40079776/e7e77a3b-68e9-4dbb-909d-9605202d8016)

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please use Flink 1.14 or 1.16.

**Comment by aiwenmo** [comment]
Of course, you can extend code to support this feature.
