### ISSUE TITLE
[Bug] [Native K8s] java.io.IOException: Error on ZipFile /opt/flink/dep.zip

### ISSUE THREAD

**Issue by ulnit** [DataLinkDC/dinky#2426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

sed: couldn't open temporary file /opt/flink/conf/sed7vQt7t: Read-only file system
2023-10-24T09:57:11.228055018+08:00 sed: couldn't open temporary file /opt/flink/conf/sed3VetvZ: Read-only file system
2023-10-24T09:57:11.239495862+08:00 /docker-entrypoint.sh: line 73: /opt/flink/conf/flink-conf.yaml: Read-only file system
/docker-entrypoint.sh: line 89: /opt/flink/conf/flink-conf.yaml.tmp: Read-only file system
2023-10-24T09:57:14.581034918+08:00 Starting kubernetes-application as a console application on host testflinksql-bfcc9dbc8-8v5jg.
2023-10-24T09:57:15.957720706+08:00 ERROR StatusLogger Reconfiguration failed: No configuration found for '1edf1c96' at 'null' in 'null'
ERROR StatusLogger Reconfiguration failed: No configuration found for '7fcf2fc1' at 'null' in 'null'
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
01:57:23.355 [flink-akka.actor.default-dispatcher-13] ERROR com.dlink.utils.ZipUtils - 压缩包处理异常，异常信息:
2023-10-24T09:57:23.363506943+08:00 java.io.IOException: Error on ZipFile /opt/flink/dep.zip
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:383) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:23.363521101+08:00 	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:261) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:230) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:23.363531374+08:00 	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:213) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:185) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:23.363542486+08:00 	at com.dlink.utils.ZipUtils.unzip(ZipUtils.java:44) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:23.363547618+08:00 	at com.dlink.app.flinksql.Submiter.loadDep(Submiter.java:258) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at com.dlink.app.flinksql.Submiter.submit(Submiter.java:161) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at com.dlink.app.MainApp.main(MainApp.java:44) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:23.363562558+08:00 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2023-10-24T09:57:23.363567709+08:00 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$2(ApplicationDispatcherBootstrap.java:254) ~[flink-dist-1.16.0.jar:1.16.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
2023-10-24T09:57:23.363674529+08:00 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
2023-10-24T09:57:23.363684358+08:00 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
	at org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:1221) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:1097) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:23.363742033+08:00 	at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:713) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:376) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	... 29 more
01:57:23.466 [flink-akka.actor.default-dispatcher-13] ERROR com.dlink.app.flinksql.Submiter - Path [/opt/flink/dep/jar] is not directory!
ERROR StatusLogger Reconfiguration failed: No configuration found for '70c1fae2' at 'null' in 'null'
01:57:27.881 [flink-akka.actor.default-dispatcher-13] ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint - Fatal error occurred in the cluster entrypoint.
2023-10-24T09:57:27.885007082+08:00 java.util.concurrent.CompletionException: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
2023-10-24T09:57:27.885014093+08:00 	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885019656+08:00 	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885043712+08:00 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885055980+08:00 	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885063739+08:00 	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:337) ~[flink-dist-1.16.0.jar:1.16.0]
2023-10-24T09:57:27.885102927+08:00 	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$2(ApplicationDispatcherBootstrap.java:254) ~[flink-dist-1.16.0.jar:1.16.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885113063+08:00 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885118567+08:00 	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
2023-10-24T09:57:27.885123836+08:00 	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
2023-10-24T09:57:27.885134705+08:00 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
2023-10-24T09:57:27.885139390+08:00 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar:1.16.0]
2023-10-24T09:57:27.885144273+08:00 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
2023-10-24T09:57:27.885149198+08:00 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
2023-10-24T09:57:27.885154036+08:00 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
2023-10-24T09:57:27.885159088+08:00 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
2023-10-24T09:57:27.885164274+08:00 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	... 14 more
2023-10-24T09:57:27.885180552+08:00 Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Querying an unbounded table 'default_catalog.foo.uat_us_opt_instrument' in batch mode is not allowed. The table source is unbounded.
2023-10-24T09:57:27.885185503+08:00 	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist-1.16.0.jar:1.16.0]
2023-10-24T09:57:27.885190269+08:00 	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist-1.16.0.jar:1.16.0]
2023-10-24T09:57:27.885195396+08:00 	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-dist-1.16.0.jar:1.16.0]
	... 13 more
2023-10-24T09:57:27.885215299+08:00 Caused by: org.apache.flink.table.api.ValidationException: Querying an unbounded table 'default_catalog.foo.uat_us_opt_instrument' in batch mode is not allowed. The table source is unbounded.
2023-10-24T09:57:27.885220061+08:00 	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.validateScanSourceForBatch(DynamicSourceUtils.java:522) ~[?:?]
2023-10-24T09:57:27.885225121+08:00 	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.validateScanSource(DynamicSourceUtils.java:468) ~[?:?]
2023-10-24T09:57:27.885229782+08:00 	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.prepareDynamicSource(DynamicSourceUtils.java:158) ~[?:?]
2023-10-24T09:57:27.885259834+08:00 	at org.apache.flink.table.planner.connectors.DynamicSourceUtils.convertSourceToRel(DynamicSourceUtils.java:122) ~[?:?]
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:118) ~[?:?]
2023-10-24T09:57:27.885296469+08:00 	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3619) ~[?:?]
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2559) ~[?:?]
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2175) ~[?:?]
2023-10-24T09:57:27.885311087+08:00 	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2095) ~[?:?]
2023-10-24T09:57:27.885315858+08:00 	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2038) ~[?:?]
2023-10-24T09:57:27.885320649+08:00 	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:669) ~[?:?]
2023-10-24T09:57:27.885325652+08:00 	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:657) ~[?:?]
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3462) ~[?:?]
2023-10-24T09:57:27.885335134+08:00 	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570) ~[?:?]
2023-10-24T09:57:27.885340676+08:00 	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:215) ~[?:?]
2023-10-24T09:57:27.885349692+08:00 	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:191) ~[?:?]
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:1498) ~[?:?]
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:1253) ~[?:?]
2023-10-24T09:57:27.885365241+08:00 	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertValidatedSqlNode(SqlToOperationConverter.java:374) ~[?:?]
2023-10-24T09:57:27.885370156+08:00 	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertValidatedSqlNodeOrFail(SqlToOperationConverter.java:384) ~[?:?]
2023-10-24T09:57:27.885374916+08:00 	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:828) ~[?:?]
2023-10-24T09:57:27.885379890+08:00 	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertValidatedSqlNode(SqlToOperationConverter.java:351) ~[?:?]
2023-10-24T09:57:27.885384711+08:00 	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:262) ~[?:?]
2023-10-24T09:57:27.885389622+08:00 	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:106) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:723) ~[flink-table-api-java-uber-1.16.0.jar:1.16.0]
2023-10-24T09:57:27.885453621+08:00 	at com.dlink.executor.Executor.executeSql(Executor.java:249) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:27.885458820+08:00 	at com.dlink.executor.Executor.submitSql(Executor.java:432) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
	at com.dlink.app.flinksql.Submiter.submit(Submiter.java:216) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:27.885487983+08:00 	at com.dlink.app.MainApp.main(MainApp.java:44) ~[dlink-app-1.16-0.7.4-jar-with-dependencies.jar:?]
2023-10-24T09:57:27.885493786+08:00 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885503918+08:00 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2023-10-24T09:57:27.885509313+08:00 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist-1.16.0.jar:1.16.0]
2023-10-24T09:57:27.885521421+08:00 	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist-1.16.0.jar:1.16.0]
2023-10-24T09:57:27.885526316+08:00 	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-dist-1.16.0.jar:1.16.0]
2023-10-24T09:57:27.885533344+08:00 	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-dist-1.16.0.jar:1.16.0]
	... 13 more
WARNING: An illegal reflective access operation has occurred
2023-10-24T09:57:28.257312029+08:00 WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:/tmp/flink-rpc-akka_5585a02e-40a3-4982-bb56-a7fb4229bf1d.jar) to method java.nio.DirectByteBuffer.cleaner()
2023-10-24T09:57:28.257319713+08:00 WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2023-10-24T09:57:28.257330601+08:00 WARNING: All illegal access operations will be denied in a future release

### What you expected to happen

no fatal error

### How to reproduce

configure native flinkOnK8s cluster，then submit job to cluster 

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Remove all configuration of docker.
