### ISSUE TITLE
[Bug] In data synchronization between Oracles, the internal query of the number type field is garbled and the real value is lost.

### ISSUE THREAD

**Issue by tttzzzwww** [DataLinkDC/dinky#2505]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

滴，咨询下大哥们：
版本：flink1.16.2 和 dinky0.7.4创建Oracle-Oracle同步任务，实例运行正常，但日志显示dlink-client模块中Number类型字段值查询乱码，具体错误信息：
例如："ID":"ew=="， ID字段类型：number，长度：38

2023-11-07 15:38:19,053 ERROR com.dlink.cdc.AbstractSinkBuilder                            [] - SchameTable: ZHYZ.DIM_HYDM1 - Row: {"before":null,"after":{"CODE":"12","NAME":"123","LEVEL_NAME":"123","STATE":"123","CHOOSE":"123","PARENT_CODE":"123","ID":"ew==","PARENT_ID":null,"FILTER_ORD":null},"source":{"version":"1.9.7.Final","connector":"oracle","name":"oracle_logminer","ts_ms":1699371497000,"snapshot":"last","db":"ORCL","sequence":null,"schema":"ZHYZ","table":"DIM_HYDM1","txId":null,"scn":"705035488","commit_scn":null,"lcr_position":null,"rs_id":null,"ssn":0,"redo_thread":null},"op":"r","ts_ms":1699342698924,"transaction":null} - Exception:
java.lang.NumberFormatException: Not a digit.
	at java.math.BigDecimal.parseExp(BigDecimal.java:675) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:512) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:401) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:834) ~[?:?]
	at com.dlink.cdc.sql.SQLSinkBuilder.convertValue(SQLSinkBuilder.java:359) ~[dlink-client-1.16-0.7.4.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:126) [dlink-client-1.16-0.7.4.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$1.flatMap(SQLSinkBuilder.java:114) [dlink-client-1.16-0.7.4.jar:?]
	at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:68) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:62) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.ProcessOperator$ContextImpl.output(ProcessOperator.java:103) [flink-dist-1.16.2.jar:1.16.2]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:293) [dlink-client-1.16-0.7.4.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:280) [dlink-client-1.16-0.7.4.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103) [flink-dist-1.16.2.jar:1.16.2]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.emitRecordsUnderCheckpointLock(DebeziumChangeFetcher.java:259) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.handleBatch(DebeziumChangeFetcher.java:244) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.runFetchLoop(DebeziumChangeFetcher.java:150) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:449) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:333) [flink-dist-1.16.2.jar:1.16.2]
2023-11-07 15:38:19,053 ERROR com.dlink.cdc.AbstractSinkBuilder                            [] - Could not forward element to next operator
org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:99) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:68) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:62) ~[flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.ProcessOperator$ContextImpl.output(ProcessOperator.java:103) ~[flink-dist-1.16.2.jar:1.16.2]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:293) [dlink-client-1.16-0.7.4.jar:?]
	at com.dlink.cdc.sql.SQLSinkBuilder$3.processElement(SQLSinkBuilder.java:280) [dlink-client-1.16-0.7.4.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103) [flink-dist-1.16.2.jar:1.16.2]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.emitRecordsUnderCheckpointLock(DebeziumChangeFetcher.java:259) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.handleBatch(DebeziumChangeFetcher.java:244) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.debezium.internal.DebeziumChangeFetcher.runFetchLoop(DebeziumChangeFetcher.java:150) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at com.ververica.cdc.debezium.DebeziumSourceFunction.run(DebeziumSourceFunction.java:449) [flink-sql-connector-mysql-cdc-2.4-SNAPSHOT.jar:2.4-SNAPSHOT]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) [flink-dist-1.16.2.jar:1.16.2]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:333) [flink-dist-1.16.2.jar:1.16.2]
Caused by: java.lang.NumberFormatException: Not a digit.

### What you expected to happen

正常使用Oracle同步功能

### How to reproduce

EXECUTE CDCSOURCE SUCCEZ_TEST.sqlplus-BZDIP.testOracle_1 WITH (
   'connector' = 'oracle-cdc',
   'hostname' = '192.168.10.205',
   'port' = '1521',
   'username' = 'succez_test',
   'password' = 'xxxxxx',
   'database-name' = 'orcl',
   'parallelism' = '1',
   'checkpoint' = '3000',
   'scan.startup.mode' = 'initial',
   'table-name' = 'SUCCEZ_TEST\.TEST_TABLE',
   'debezium.database.history.store.only.captured.tables.ddl' = 'true',
   'debezium.database.tablename.case.insensitive' = 'false',
   'debezium.log.mining.strategy' = 'online_catalog',
   'sink.table.prefix' = 'ODS_',
   'sink.table-name' = '${tableName}',
   'sink.connector' = 'jdbc',
   'sink.url' = 'jdbc:oracle:thin:@//192.168.10.25:1521/ws',
   'sink.username' = 'bzdip',
   'sink.password' = 'xxxxxx'
)

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tttzzzwww** [comment]
debezium.decimal.handling.mode' = 'string' 即可解决Flink-CDC读取Decimal等数值类型变成了非数值字符串问题, 具体可参考debezium官方说明：https://debezium.io/documentation/reference/1.5/connectors/oracle.html#oracle-property-decimal-handling-mode
