### ISSUE TITLE
[Bug] [NullPointerException] Starting the flink 1.15 session fails

### ISSUE THREAD

**Issue by RainbowWS** [DataLinkDC/dinky#2778]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Flink 1.15.3 
dinky 1.0.0-rc1 
cdh 6.2.0  
hdfs 3.0.0+cdh6.2.0
hive 2.1.1+cdh6.2.0

单节点（不是集群节点）向集群提交任务。（7.0版本试过可以提交没有问题）

<img width="1025" alt="9cf6cefa23d1c6d6ceeb87b16290ca82" src="https://github.com/DataLinkDC/dinky/assets/37372204/80d8cf07-d35f-41c3-b4a5-a8827a11e077">
录入flink 集群信息，并配置当前所有相关配置，将flink lib上传到hdfs和配置好相关路径，点击启动，日志信息如下。截图如下

```
[dinky] 2023-12-25 17:16:58 HKT INFO  org.springframework.web.socket.config.WebSocketMessageBrokerStats 128 lambda$initLoggingTask$0 - WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 3, active threads = 1, queued tasks = 0, completed tasks = 2]
[dinky] 2023-12-25 17:31:22 HKT ERROR org.dinky.context.SseSessionContextHolder 128 onError - Type: SseSession [5497741c-91a9-4eee-b28d-71eb04153e8c] Error, Message: Broken pipe
[dinky] 2023-12-25 17:31:22 HKT ERROR org.dinky.context.SseSessionContextHolder 162 lambda$sendTopic$3 - Error sending sse data:java.io.IOException: Broken pipe
[dinky] 2023-12-25 17:31:22 HKT ERROR org.dinky.context.SseSessionContextHolder 128 onError - Type: SseSession [5497741c-91a9-4eee-b28d-71eb04153e8c] Error, Message: java.io.IOException: Broken pipe
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.rpc.address, localhost
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.rpc.port, 6123
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.bind-host, localhost
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.memory.process.size, 1600m
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.bind-host, localhost
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.host, localhost
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.memory.process.size, 1728m
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: taskmanager.numberOfTaskSlots, 4
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: parallelism.default, 1
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: yarn.application-attempts, 5
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.interval, 3min
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.timeout, 10min
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.checkpoints.dir, hdfs://xxx:8020/flink/flink-checkpoints
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.checkpoints.num-retained, 10
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: execution.checkpointing.externalized-checkpoint-retention, RETAIN_ON_CANCELLATION
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: state.savepoints.dir, hdfs://xxx:8020/flink/flink-savepoints
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.execution.failover-strategy, region
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: restart-strategy, fixed-delay
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: restart-strategy.fixed-delay.attempts, 10
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: restart-strategy.fixed-delay.delay, 10 s
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: rest.port, 8081
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: rest.address, localhost
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: rest.bind-port, 8080-8090
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: rest.bind-address, localhost
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: jobmanager.archive.fs.dir, hdfs://xxx:8020/flink/completed-jobs/
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: historyserver.web.address, 172.16.74.234
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: historyserver.web.port, 8082
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: historyserver.archive.fs.dir, hdfs://xxx:8020/flink/completed-jobs/
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: historyserver.archive.fs.refresh-interval, 10000
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.configuration.GlobalConfiguration 213 loadYAMLResource - Loading configuration property: env.java.opts, -Dfile.encoding=UTF-8
[dinky] 2023-12-25 17:31:36 HKT WARN  org.apache.flink.yarn.configuration.YarnLogConfigUtil 73 discoverLogConfigFile - The configuration directory ('/usr/data/flink/conf') already contains a LOG4J config file.If you want to use logback, then please delete or rename the log configuration file.
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.hadoop.yarn.client.RMProxy 98 createRMProxy - Connecting to ResourceManager at xxx:8032
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.yarn.YarnClusterDescriptor 208 getLocalFlinkDistPath - No path for the flink jar passed. Using the location of class org.apache.flink.yarn.YarnClusterDescriptor to locate the jar
[dinky] 2023-12-25 17:31:36 HKT INFO  org.apache.flink.yarn.YarnClusterDescriptor 563 deployInternal - Cluster specification: ClusterSpecification{masterMemoryMB=2048, taskManagerMemoryMB=6144, slotsPerTaskManager=10}
[dinky] 2023-12-25 17:31:36 HKT WARN  org.apache.flink.core.plugin.PluginConfig 69 getPluginsDir - The plugins directory [plugins] does not exist.
[dinky] 2023-12-25 17:15:01 HKT ERROR org.dinky.aop.exception.UnKnownExceptionHandler 39 unknownException - null java.lang.NullPointerException: null
	at org.dinky.service.impl.ClusterInstanceServiceImpl.deploySessionCluster(ClusterInstanceServiceImpl.java:207) ~[dinky-admin-1.0.0-rc1.jar:?]
	at org.dinky.service.impl.ClusterInstanceServiceImpl$$FastClassBySpringCGLIB$$b1f0defa.invoke(<generated>) ~[dinky-admin-1.0.0-rc1.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.service.impl.ClusterInstanceServiceImpl$$EnhancerBySpringCGLIB$$ee7b894b.deploySessionCluster(<generated>) ~[dinky-admin-1.0.0-rc1.jar:?]
	at org.dinky.controller.ClusterInstanceController.deploySessionClusterInstance(ClusterInstanceController.java:258) ~[dinky-admin-1.0.0-rc1.jar:?]
	at org.dinky.controller.ClusterInstanceController$$FastClassBySpringCGLIB$$a81c9eda.invoke(<generated>) ~[dinky-admin-1.0.0-rc1.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.controller.ClusterInstanceController$$EnhancerBySpringCGLIB$$9c6fbe4.deploySessionClusterInstance(<generated>) ~[dinky-admin-1.0.0-rc1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:558) ~[tomcat-embed-core-9.0.74.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.74.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124) ~[druid-1.2.8.jar:1.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at cn.dev33.satoken.filter.SaPathCheckFilterForServlet.doFilter(SaPathCheckFilterForServlet.java:55) ~[sa-token-spring-boot-starter-1.37.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.11.jar:2.7.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_311]
```

![image](https://github.com/DataLinkDC/dinky/assets/37372204/0d138bd4-ee0e-4fe4-9b3b-369922897ba7)
![image](https://github.com/DataLinkDC/dinky/assets/37372204/82ef5dee-7a86-42b1-be33-e18e21444db7)

 

### What you expected to happen

启动出现空指针，不知道是否为配置问题

### How to reproduce

新建点击运行

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这个问题是由于在 yarn 创建 Flink session 集群时遇到了问题导致创建失败，从而触发了后续的空指针。
失败的原因需要手动查看 yarn 的 app 日志，常见的原因有资源不够、hdfs 路径下缺少依赖、JM端口号冲突等。
