### ISSUE TITLE
[Bug] [CDC] CDC synchronization is not compatible with the different table structures of mysql table and starrocks table

### ISSUE THREAD

**Issue by microxxx** [DataLinkDC/dinky#2914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

EXECUTE CDCSOURCE test_insurance_sysc WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '192.168.0.181',
  'port' = '3306',
  'username' = 'test',
  'password' = '123456',
  'checkpoint' = '300000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'test\.store_insurance_order',
  'sink.connector' = 'starrocks',
  'sink.jdbc-url' = 'jdbc:mysql://192.168.0.182:19030',
  'sink.load-url' = '192.168.0.182:18030',
  'sink.username' = 'test',
  'sink.password' = '123456',
  'sink.sink.db' = 'test',
  'sink.table.prefix' = 'ods_',
  'sink.table.lower' = 'true',
  'sink.database-name' = 'test',
  'sink.table-name' = 'ods_store_insurance_order',
  'sink.sink.properties.format' = 'json',
  'sink.sink.properties.strip_outer_array' = 'true',
  'sink.sink.max-retries' = '10',
  'sink.sink.buffer-flush.interval-ms' = '15000',
  'sink.sink.parallelism' = '1'
)
执行以上语句，由于源表mysql 和starrocks 表的primary key 不同（其实业务库和分析库结构不同也正常），导致数据并不能同步。
[dlink] 2024-01-05 09:40:25 CST ERROR com.dlink.trans.ddl.CreateCDCSourceOperation 200 build - Primary keys of the flink `TableSchema` do not match with the ones from starrocks table. java.lang.IllegalArgumentException: Primary keys of the flink `TableSchema` do not match with the ones from starrocks table.
	at com.starrocks.connector.flink.manager.StarRocksSinkTable.validateTableStructure(StarRocksSinkTable.java:118) ~[flink-connector-starrocks-1.2.9_flink-1.16.jar:?]
	at com.starrocks.connector.flink.table.sink.StarRocksDynamicSinkFunctionV2.<init>(StarRocksDynamicSinkFunctionV2.java:104) ~[flink-connector-starrocks-1.2.9_flink-1.16.jar:?]
	at com.starrocks.connector.flink.table.sink.SinkFunctionFactory.createSinkFunction(SinkFunctionFactory.java:108) ~[flink-connector-starrocks-1.2.9_flink-1.16.jar:?]
	at com.starrocks.connector.flink.table.sink.StarRocksDynamicTableSink.getSinkRuntimeProvider(StarRocksDynamicTableSink.java:56) ~[flink-connector-starrocks-1.2.9_flink-1.16.jar:?]
	at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecSink.createSinkTransformation(CommonExecSink.java:150) ~[?:?]
	at org.apache.flink.table.planner.plan.nodes.exec.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.java:176) ~[?:?]
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:159) ~[?:?]
	at org.apache.flink.table.planner.delegation.StreamPlanner.$anonfun$translateToPlan$1(StreamPlanner.scala:85) ~[?:?]
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233) ~[flink-scala_2.12-1.16.3.jar:1.16.3]
	at scala.collection.Iterator.foreach(Iterator.scala:937) ~[flink-scala_2.12-1.16.3.jar:1.16.3]
	at scala.collection.Iterator.foreach$(Iterator.scala:937) ~[flink-scala_2.12-1.16.3.jar:1.16.3]

同时还会报

[dlink] 2024-01-05 09:05:28 CST ERROR com.alibaba.druid.stat.DruidDataSourceStatManager 165 addDataSource - register mbean error javax.management.MalformedObjectNameException: Invalid character '=' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618) ~[?:1.8.0_212]
	at javax.management.ObjectName.<init>(ObjectName.java:1382) ~[?:1.8.0_212]
	at com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(DruidDataSourceStatManager.java:162) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$1.run(DruidDataSource.java:2154) ~[druid-1.2.8.jar:1.2.8]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]

### What you expected to happen

期望数据可以在正常适配过后进行同步

### How to reproduce

mysql和starrocks 表结构primary key 不同即可

### Version

0.7.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by microxxx** [comment]
增加primary key

**Comment by Zzm0809** [comment]
同步场景下 必须保证端到端库表一致 这是基操
