### ISSUE TITLE
[Bug] [dinky-admin ] Caused by: java.lang.ClassNotFoundException: org.apache.flink.configuration.ConfigOption 

### ISSUE THREAD

**Issue by SnJForever** [DataLinkDC/dinky#3008]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

[dinky] 2024-01-16 01:42:36.331  ERROR    25 --- [io-8888-exec-10] org.dinky.aop.exception.UnKnownExceptionHandler: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Lorg/apache/flink/configuration/ConfigOption;
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Lorg/apache/flink/configuration/ConfigOption;
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1087) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) ~[tomcat-embed-core-9.0.74.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.74.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124) ~[druid-1.2.8.jar:1.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at cn.dev33.satoken.filter.SaPathCheckFilterForServlet.doFilter(SaPathCheckFilterForServlet.java:55) ~[sa-token-spring-boot-starter-1.37.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.11.jar:2.7.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_342]
Caused by: java.lang.NoClassDefFoundError: Lorg/apache/flink/configuration/ConfigOption;
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_342]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_342]
	at java.lang.Class.getDeclaredFields(Class.java:1916) ~[?:1.8.0_342]
	at cn.hutool.core.util.ReflectUtil.getFieldsDirectly(ReflectUtil.java:215) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.util.ReflectUtil.lambda$getFields$54eedd5e$1(ReflectUtil.java:181) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.lang.func.Func0.callWithRuntimeException(Func0.java:36) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.lambda$computeIfAbsent$3(ReferenceConcurrentMap.java:154) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.lambda$computeIfAbsent$1(ReferenceConcurrentMap.java:137) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.MapUtil.computeIfAbsentForJdk8(MapUtil.java:1507) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.SafeConcurrentHashMap.computeIfAbsent(SafeConcurrentHashMap.java:75) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.computeIfAbsent(ReferenceConcurrentMap.java:137) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.computeIfAbsent(ReferenceConcurrentMap.java:154) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.util.ReflectUtil.getFields(ReflectUtil.java:181) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.util.ReflectUtil.getFields(ReflectUtil.java:196) ~[hutool-all-5.8.24.jar:5.8.24]
	at org.dinky.utils.FlinkConfigOptionsUtils.loadOptionsByClassName(FlinkConfigOptionsUtils.java:56) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.service.impl.SuggestionServiceImpl.buildFlinkConfSuggestions(SuggestionServiceImpl.java:140) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.service.impl.SuggestionServiceImpl.getSuggestions(SuggestionServiceImpl.java:71) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.controller.SuggestionController.queryAllSuggestions(SuggestionController.java:53) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.controller.SuggestionController$$FastClassBySpringCGLIB$$5f4bd631.invoke(<generated>) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.controller.SuggestionController$$EnhancerBySpringCGLIB$$608c899.queryAllSuggestions(<generated>) ~[dinky-admin-1.0.0-rc3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]
	... 53 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.configuration.ConfigOption
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_342]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_342]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_342]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_342]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_342]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_342]
	at java.lang.Class.getDeclaredFields(Class.java:1916) ~[?:1.8.0_342]
	at cn.hutool.core.util.ReflectUtil.getFieldsDirectly(ReflectUtil.java:215) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.util.ReflectUtil.lambda$getFields$54eedd5e$1(ReflectUtil.java:181) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.lang.func.Func0.callWithRuntimeException(Func0.java:36) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.lambda$computeIfAbsent$3(ReferenceConcurrentMap.java:154) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.lambda$computeIfAbsent$1(ReferenceConcurrentMap.java:137) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.MapUtil.computeIfAbsentForJdk8(MapUtil.java:1507) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.SafeConcurrentHashMap.computeIfAbsent(SafeConcurrentHashMap.java:75) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.computeIfAbsent(ReferenceConcurrentMap.java:137) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.map.ReferenceConcurrentMap.computeIfAbsent(ReferenceConcurrentMap.java:154) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.util.ReflectUtil.getFields(ReflectUtil.java:181) ~[hutool-all-5.8.24.jar:5.8.24]
	at cn.hutool.core.util.ReflectUtil.getFields(ReflectUtil.java:196) ~[hutool-all-5.8.24.jar:5.8.24]
	at org.dinky.utils.FlinkConfigOptionsUtils.loadOptionsByClassName(FlinkConfigOptionsUtils.java:56) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.service.impl.SuggestionServiceImpl.buildFlinkConfSuggestions(SuggestionServiceImpl.java:140) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.service.impl.SuggestionServiceImpl.getSuggestions(SuggestionServiceImpl.java:71) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.controller.SuggestionController.queryAllSuggestions(SuggestionController.java:53) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.dinky.controller.SuggestionController$$FastClassBySpringCGLIB$$5f4bd631.invoke(<generated>) ~[dinky-admin-1.0.0-rc3.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.controller.SuggestionController$$EnhancerBySpringCGLIB$$608c899.queryAllSuggestions(<generated>) ~[dinky-admin-1.0.0-rc3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]

### What you expected to happen

don`t hive error

### How to reproduce

1.docker run the dinky with version 1.0.0-rc3
2.create a mysql task，the web page display "Something went wrong."

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
环境问题 自行看官网

**Comment by SnJForever** [comment]
官网没有找到这个问题的解决办法，麻烦给下链接，如果你说的是依赖包没有添加的话，我已经添加了依赖，但是不起作用

**Comment by aiwenmo** [comment]
How was it added? Can you provide a detailed description?

**Comment by stevenkitter** [comment]
chose dev profiles, because flink driver is import only in dev. Not prod.

**Comment by LiuJinKai1998** [comment]
> 官网没有找到这个问题的解决办法，麻烦给下链接，如果你说的是依赖包没有添加的话，我已经添加了依赖，但是不起作用

有什么解决方法吗，我切换到dev profiles启动也不行

**Comment by Zzm0809** [comment]
> > 官网没有找到这个问题的解决办法，麻烦给下链接，如果你说的是依赖包没有添加的话，我已经添加了依赖，但是不起作用
> 
> 有什么解决方法吗，我切换到dev profiles启动也不行

https://www.dinky.org.cn/docs/next/developer_guide/local_debug

**Comment by LiuJinKai1998** [comment]
> > > 官网没有找到这个问题的解决办法，麻烦给下链接，如果你说的是依赖包没有添加的话，我已经添加了依赖，但是不起作用
> > 
> > 
> > 有什么解决方法吗，我切换到dev profiles启动也不行
> 
> https://www.dinky.org.cn/docs/next/developer_guide/local_debug

好的，选择dev的时候，好像maven-central也需要一起选中才行，但文档里面的截图都没有选中maven-central
