### ISSUE TITLE
Error creating mapping relationship for table field ‘time’ type in cdcsource task creation，string to time(0)

### ISSUE THREAD

**Issue by liukundong** [DataLinkDC/dinky#3065]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

mysql源表创建时字段使用了time类型，创建任务时报错，query schema使用的是string，而sink创建的时候是time(0)，导致任务无法提交。

### What you expected to happen

Query schema: [id: STRING, customer_id: STRING, name: STRING, mobile_no: STRING, id_card: STRING, id_card_pic1: STRING, id_card_pic2: STRING, station: STRING, station_code: STRING, service_date: DATE, **time_from: STRING, time_to: STRING**, time_range: STRING, state: INT, response: STRING, rating: INT, reward: INT, operator_name: STRING, operator_id: STRING, cancel_flag: INT, hide_flag: INT, del_flag: BOOLEAN, creator: STRING, create_time: TIMESTAMP(9), modifier: STRING, modify_time: TIMESTAMP(9), delete_time: TIMESTAMP(9)]
Sink schema:  [id: STRING, customer_id: STRING, name: STRING, mobile_no: STRING, id_card: STRING, id_card_pic1: STRING, id_card_pic2: STRING, station: STRING, station_code: STRING, service_date: DATE, **time_from: TIME(0), time_to: TIME(0)**, time_range: STRING, state: INT, response: STRING, rating: INT, reward: INT, operator_name: STRING, operator_id: STRING, cancel_flag: INT, hide_flag: INT, del_flag: BOOLEAN, creator: STRING, create_time: TIMESTAMP(6), modifier: STRING, modify_time: TIMESTAMP(6), delete_time: TIMESTAMP(6)] org.apache.flink.table.api.ValidationException: Column types of query result and sink for 'default_catalog.default_database.xxxxxxxxx' do not match.
Cause: Incompatible types for sink column 'time_from' at position 10.

### How to reproduce

Query schema: [id: STRING, customer_id: STRING, name: STRING, mobile_no: STRING, id_card: STRING, id_card_pic1: STRING, id_card_pic2: STRING, station: STRING, station_code: STRING, service_date: DATE, **time_from: STRING, time_to: STRING**, time_range: STRING, state: INT, response: STRING, rating: INT, reward: INT, operator_name: STRING, operator_id: STRING, cancel_flag: INT, hide_flag: INT, del_flag: BOOLEAN, creator: STRING, create_time: TIMESTAMP(9), modifier: STRING, modify_time: TIMESTAMP(9), delete_time: TIMESTAMP(9)]
Sink schema:  [id: STRING, customer_id: STRING, name: STRING, mobile_no: STRING, id_card: STRING, id_card_pic1: STRING, id_card_pic2: STRING, station: STRING, station_code: STRING, service_date: DATE, **time_from: TIME(0), time_to: TIME(0)**, time_range: STRING, state: INT, response: STRING, rating: INT, reward: INT, operator_name: STRING, operator_id: STRING, cancel_flag: INT, hide_flag: INT, del_flag: BOOLEAN, creator: STRING, create_time: TIMESTAMP(6), modifier: STRING, modify_time: TIMESTAMP(6), delete_time: TIMESTAMP(6)] org.apache.flink.table.api.ValidationException: Column types of query result and sink for 'default_catalog.default_database.xxxxxxxxx' do not match.
Cause: Incompatible types for sink column 'time_from' at position 10.

### Anything else

Query schema: [id: STRING, customer_id: STRING, name: STRING, mobile_no: STRING, id_card: STRING, id_card_pic1: STRING, id_card_pic2: STRING, station: STRING, station_code: STRING, service_date: DATE, **time_from: STRING, time_to: STRING**, time_range: STRING, state: INT, response: STRING, rating: INT, reward: INT, operator_name: STRING, operator_id: STRING, cancel_flag: INT, hide_flag: INT, del_flag: BOOLEAN, creator: STRING, create_time: TIMESTAMP(9), modifier: STRING, modify_time: TIMESTAMP(9), delete_time: TIMESTAMP(9)]
Sink schema:  [id: STRING, customer_id: STRING, name: STRING, mobile_no: STRING, id_card: STRING, id_card_pic1: STRING, id_card_pic2: STRING, station: STRING, station_code: STRING, service_date: DATE, **time_from: TIME(0), time_to: TIME(0)**, time_range: STRING, state: INT, response: STRING, rating: INT, reward: INT, operator_name: STRING, operator_id: STRING, cancel_flag: INT, hide_flag: INT, del_flag: BOOLEAN, creator: STRING, create_time: TIMESTAMP(6), modifier: STRING, modify_time: TIMESTAMP(6), delete_time: TIMESTAMP(6)] org.apache.flink.table.api.ValidationException: Column types of query result and sink for 'default_catalog.default_database.xxxxxxxxx' do not match.
Cause: Incompatible types for sink column 'time_from' at position 10.

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liukundong** [comment]
补充一下，是在整库同步的时候出现的

**Comment by aiwenmo** [comment]
What is your Dinky version?

**Comment by liukundong** [comment]
> What is your Dinky version?

v1.0.0_rc3_flink_1.18

**Comment by liukundong** [comment]
> What is your Dinky version?

这个bug是否有解决呢？下载了最新的v1.0.0_rc4 问题依然存在

**Comment by liukundong** [comment]
> What is your Dinky version?

Has this bug been resolved?

**Comment by Zzm0809** [comment]
> > What is your Dinky version?
> 
> Has this bug been resolved?

You can try to fix this problem

**Comment by liukundong** [comment]
> > > What is your Dinky version?
> > 
> > 
> > Has this bug been resolved?
> 
> You can try to fix this problem

how to fix it？

**Comment by 617450941** [comment]
实测问题没有彻底解决 还有新的报错 报错信息如下
2024-10-11 10:22:43,988 ERROR org.dinky.cdc.AbstractSinkBuilder                            [] - SchemaTable: db1001_store.tc_typography_reservation - Row: {"before":null,"after":{"id":1369338093790721,"enterprise_id":1583,"shop_id":2105,"create_time":1728613363844,"create_user":1178580942544384,"md5":"b327f9a7b0d03e3f95666a3c43b88fa34716b701","process":2,"reservation":1,"reservation_shop_id":2105,"reservation_time":31800000000,"reservation_date":1729180800000,"label_category_id":null,"group_type_category_id":1178959973829633,"is_online":false,"control_type":0,"operation_type":0,"notice_status":false,"remark":"拍4套服装","is_delete":false,"notice_method":null,"template_time_text":"08:50","notice_remark":null,"reservation_num":1,"color_id":null,"color":null},"source":{"version":"1.9.8.Final","connector":"mysql","name":"mysql_binlog_source","ts_ms":1728613363000,"snapshot":"false","db":"db1001_store","sequence":null,"table":"tc_typography_reservation","server_id":26411466,"gtid":"35bb68e1-a470-11ea-8f8f-b8599fe81220:11064290618","file":"mysql-bin.033795","pos":260825941,"row":0,"thread":1201706943,"query":null},"op":"c","ts_ms":1728613362286,"transaction":null} - Exception org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator 2024-10-11 10:22:43,988 ERROR org.dinky.cdc.AbstractSinkBuilder                            [] - Could not forward element to next operator org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:110) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:83) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.ProcessOperator$ContextImpl.output(ProcessOperator.java:103) ~[flink-dist-1.18.1.jar:1.18.1] at org.dinky.cdc.sql.AbstractSqlSinkBuilder$1.processElement(AbstractSqlSinkBuilder.java:179) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.dinky.cdc.sql.AbstractSqlSinkBuilder$1.processElement(AbstractSqlSinkBuilder.java:172) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:77) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:39) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:77) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:39) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask$AsyncDataOutputToOutput.emitRecord(SourceOperatorStreamTask.java:309) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:110) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:101) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter$OutputCollector.collect(MySqlRecordEmitter.java:141) ~[flink-cdc-pipeline-connector-mysql-3.1.0.jar:3.1.0] at org.apache.flink.cdc.debezium.JsonDebeziumDeserializationSchema.deserialize(JsonDebeziumDeserializationSchema.java:73) ~[flink-cdc-pipeline-connector-mysql-3.1.0.jar:3.1.0] at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitElement(MySqlRecordEmitter.java:119) ~[flink-cdc-pipeline-connector-mysql-3.1.0.jar:3.1.0] at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.processElement(MySqlRecordEmitter.java:101) ~[flink-cdc-pipeline-connector-mysql-3.1.0.jar:3.1.0] at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:73) ~[flink-cdc-pipeline-connector-mysql-3.1.0.jar:3.1.0] at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:46) ~[flink-cdc-pipeline-connector-mysql-3.1.0.jar:3.1.0] at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:160) ~[flink-connector-files-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:419) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:562) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:858) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:807) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953) [flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:932) [flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746) [flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) [flink-dist-1.18.1.jar:1.18.1] at java.lang.Thread.run(Unknown Source) [?:?] Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:110) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:77) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:39) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51) ~[flink-dist-1.18.1.jar:1.18.1] at org.dinky.cdc.sql.AbstractSqlSinkBuilder.rowCollect(AbstractSqlSinkBuilder.java:112) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.dinky.cdc.sql.AbstractSqlSinkBuilder.lambda$sqlSinkRowFunction$2af4781a$1(AbstractSqlSinkBuilder.java:78) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108) ~[flink-dist-1.18.1.jar:1.18.1] ... 34 more Caused by: org.apache.flink.util.FlinkRuntimeException: Error during input conversion from external DataStream API to internal Table API data structures. Make sure that the provided data types that configure the converters are correctly declared in the schema. Affected record: +I[1369338093790721, 1583, 2105, 1728613363844, 1178580942544384, b327f9a7b0d03e3f95666a3c43b88fa34716b701, 2, 1, 2105, 31800000000, 1729180800000, null, 1178959973829633, false, 0, 0, false, 拍4套服装, false, null, 08:50, null, 1, null, null] at org.apache.flink.table.runtime.operators.source.InputConversionOperator.processElement(InputConversionOperator.java:95) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:77) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:39) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51) ~[flink-dist-1.18.1.jar:1.18.1] at org.dinky.cdc.sql.AbstractSqlSinkBuilder.rowCollect(AbstractSqlSinkBuilder.java:112) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.dinky.cdc.sql.AbstractSqlSinkBuilder.lambda$sqlSinkRowFunction$2af4781a$1(AbstractSqlSinkBuilder.java:78) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108) ~[flink-dist-1.18.1.jar:1.18.1] ... 34 more Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.time.LocalTime (java.lang.Long and java.time.LocalTime are in module java.base of loader 'bootstrap') at org.apache.flink.table.data.conversion.TimeLocalTimeConverter.toInternal(TimeLocalTimeConverter.java:26) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.table.data.conversion.DataStructureConverter.toInternalOrNull(DataStructureConverter.java:61) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.table.data.conversion.RowRowConverter.toInternal(RowRowConverter.java:75) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.table.data.conversion.RowRowConverter.toInternal(RowRowConverter.java:37) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.table.data.conversion.DataStructureConverter.toInternalOrNull(DataStructureConverter.java:61) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.table.runtime.connector.source.DataStructureConverterWrapper.toInternal(DataStructureConverterWrapper.java:51) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.table.runtime.operators.source.InputConversionOperator.processElement(InputConversionOperator.java:92) ~[flink-table-runtime-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:77) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:39) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51) ~[flink-dist-1.18.1.jar:1.18.1] at org.dinky.cdc.sql.AbstractSqlSinkBuilder.rowCollect(AbstractSqlSinkBuilder.java:112) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.dinky.cdc.sql.AbstractSqlSinkBuilder.lambda$sqlSinkRowFunction$2af4781a$1(AbstractSqlSinkBuilder.java:78) ~[dinky-app-1.18-1.1.0-jar-with-dependencies.jar:?] at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) ~[flink-dist-1.18.1.jar:1.18.1] at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:108) ~[flink-dist-1.18.1.jar:1.18.1] ... 34 more
