### ISSUE TITLE
[Bug] Flink-SQL check backend error

### ISSUE THREAD

**Issue by suiquantong** [DataLinkDC/dinky#3067]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky：1.0.0 -rt3
flink：1.16.3  
在本地执行sql 代码检查    没有问题 在服务器上执行 后端报错 前端不提示任何错误

```sql

EXECUTE CDCSOURCE cdc_mysql
WITH
  (
    'connector' = 'mysql-cdc',
    'hostname' = '172.18.1.85',
    'port' = '3306',
    'username' = 'root',
    'password' = 'abcd_1234',
    'checkpoint' = '3000',
    'scan.startup.mode' = 'initial',
    'parallelism' = '1',
    'table-name' = 'xxl_job\..*',
    'sink.connector' = 'jdbc',
    'sink.url' = 'jdbc:mysql://172.18.1.126:3306/xxl_job?characterEncoding=utf-8&useSSL=false',
    'sink.username' = 'root',
    'sink.password' = 'o2vMdcUaqsd',
    'sink.sink.db' = 'xxl_job',
    'sink.table.lower' = 'true',
    'sink.table-name' = '${tableName}',
    'sink.driver' = 'com.mysql.jdbc.Driver',
    'sink.sink.buffer-flush.interval' = '2s',
    'sink.sink.buffer-flush.max-rows' = '100',
    'sink.sink.max-retries' = '5',
    --  是否自动建表
    'sink.auto.create' = 'true'
  )

```

错误信息如下
```shell
Caused by: java.lang.IncompatibleClassChangeError: class org.apache.flink.sql.parser.validate.FlinkSqlConformance can not implement org.apache.calcite.sql.validate.SqlConformance, because it is not an interface (org.apache.calcite.sql.validate.SqlConformance is in unnamed module of loader 'app')
        at org.apache.flink.table.planner.delegation.PlannerContext.getSqlConformance(PlannerContext.java:268) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at org.apache.flink.table.planner.delegation.PlannerContext.lambda$getSqlParserConfig$0(PlannerContext.java:241) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
        at org.apache.flink.table.planner.delegation.PlannerContext.getSqlParserConfig(PlannerContext.java:237) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at org.apache.flink.table.planner.delegation.PlannerContext.createFrameworkConfig(PlannerContext.java:142) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at org.apache.flink.table.planner.delegation.PlannerContext.<init>(PlannerContext.java:124) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at org.apache.flink.table.planner.delegation.PlannerBase.<init>(PlannerBase.scala:121) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at org.apache.flink.table.planner.delegation.StreamPlanner.<init>(StreamPlanner.scala:65) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at org.apache.flink.table.planner.delegation.DefaultPlannerFactory.create(DefaultPlannerFactory.java:65) ~[flink-table-planner_2.12-1.16.3.jar:1.16.3]
        at org.apache.flink.table.factories.PlannerFactoryUtil.createPlanner(PlannerFactoryUtil.java:58) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
        at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.create(StreamTableEnvironmentImpl.java:127) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
        at org.apache.flink.table.api.bridge.java.StreamTableEnvironment.create(StreamTableEnvironment.java:122) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
        at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:86) ~[dinky-app-1.16-1.0.0-rc3-jar-with-dependencies.jar:?]
        at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:69) ~[dinky-app-1.16-1.0.0-rc3-jar-with-dependencies.jar:?]
        at org.dinky.executor.RemoteStreamExecutor.createCustomTableEnvironment(RemoteStreamExecutor.java:49) ~[dinky-core-1.0.0-rc3.jar:?]
        at org.dinky.executor.Executor.init(Executor.java:142) ~[dinky-core-1.0.0-rc3.jar:?]
        at org.dinky.executor.RemoteStreamExecutor.<init>(RemoteStreamExecutor.java:44) ~[dinky-core-1.0.0-rc3.jar:?]
        at org.dinky.executor.ExecutorFactory.buildRemoteExecutor(ExecutorFactory.java:68) ~[dinky-core-1.0.0-rc3.jar:?]
        at org.dinky.executor.ExecutorFactory.buildExecutor(ExecutorFactory.java:42) ~[dinky-core-1.0.0-rc3.jar:?]
        at org.dinky.job.JobManager.init(JobManager.java:220) ~[dinky-core-1.0.0-rc3.jar:?]
        at org.dinky.job.JobManager.build(JobManager.java:197) ~[dinky-core-1.0.0-rc3.jar:?]
        at org.dinky.service.task.FlinkSqlTask.getJobManager(FlinkSqlTask.java:72) ~[dinky-admin-1.0.0-rc3.jar:?]
        at org.dinky.service.task.FlinkSqlTask.<init>(FlinkSqlTask.java:51) ~[dinky-admin-1.0.0-rc3.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at cn.hutool.core.util.ReflectUtil.newInstance(ReflectUtil.java:873) ~[hutool-all-5.8.24.jar:5.8.24]
        at org.dinky.service.task.BaseTask.getTask(BaseTask.java:73) ~[dinky-admin-1.0.0-rc3.jar:?]
        at org.dinky.service.impl.TaskServiceImpl.explainTask(TaskServiceImpl.java:471) ~[dinky-admin-1.0.0-rc3.jar:?]
        at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.0-rc3.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
        at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.0.0-rc3.jar:?]
        ... 92 more



```

### What you expected to happen

能够正常的返回错误信息或者 正确返回

感觉像缺包 但是发现包都有 也进行了 flink-table-planner.jar 的替换了

### How to reproduce

在服务器上部署 并且执行我提供的sql 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
提供完整堆栈日志

**Comment by suiquantong** [comment]
```shell
Start Process:FlinkSubmit/14
Start Process Step:SUBMIT_PRECHECK
2024-01-25 16:43:56.979 INFO  org.dinky.service.impl.TaskServiceImpl(175): Start check and config task, task:整库CDC
Process Step SUBMIT_PRECHECK exit with status:FINISHED
Start Process Step:SUBMIT_EXECUTE
Start Process Step:SUBMIT_BUILD_CONFIG
2024-01-25 16:43:56.987 INFO  org.dinky.service.impl.TaskServiceImpl(284): Start initialize FlinkSQLEnv:
2024-01-25 16:43:56.988 INFO  org.dinky.service.impl.TaskServiceImpl(304): Initializing data permissions...
2024-01-25 16:43:56.994 INFO  org.dinky.service.impl.TaskServiceImpl(306): Finish initialize FlinkSQLEnv.
2024-01-25 16:43:56.994 INFO  org.dinky.service.impl.TaskServiceImpl(234): Init remote cluster
Process Step SUBMIT_BUILD_CONFIG exit with status:FINISHED
Process Step SUBMIT_EXECUTE exit with status:FAILED
cn.hutool.core.exceptions.UtilException: Instance class [class org.dinky.service.task.FlinkSqlTask] error!
	at cn.hutool.core.util.ReflectUtil.newInstance(ReflectUtil.java:875)
	at org.dinky.service.task.BaseTask.getTask(BaseTask.java:73)
	at org.dinky.service.impl.TaskServiceImpl.executeJob(TaskServiceImpl.java:189)
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.dinky.aop.ProcessAspect.processStepAround(ProcessAspect.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.dinky.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$cd312e3c.executeJob(<generated>)
	at org.dinky.service.impl.TaskServiceImpl.submitTask(TaskServiceImpl.java:317)
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.dinky.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$cd312e3c.submitTask(<generated>)
	at org.dinky.controller.TaskController.submitTask(TaskController.java:80)
	at org.dinky.controller.TaskController$$FastClassBySpringCGLIB$$5b68bd32.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.dinky.aop.ProcessAspect.processAround(ProcessAspect.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.dinky.controller.TaskController$$EnhancerBySpringCGLIB$$a4644d06.submitTask(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at cn.dev33.satoken.filter.SaPathCheckFilterForServlet.doFilter(SaPathCheckFilterForServlet.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at cn.hutool.core.util.ReflectUtil.newInstance(ReflectUtil.java:873)
	... 140 more
Caused by: java.lang.IncompatibleClassChangeError: class org.apache.flink.sql.parser.validate.FlinkSqlConformance can not implement org.apache.calcite.sql.validate.SqlConformance, because it is not an interface (org.apache.calcite.sql.validate.SqlConformance is in unnamed module of loader 'app')
	at org.apache.flink.table.planner.delegation.PlannerContext.getSqlConformance(PlannerContext.java:268)
	at org.apache.flink.table.planner.delegation.PlannerContext.lambda$getSqlParserConfig$0(PlannerContext.java:241)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.apache.flink.table.planner.delegation.PlannerContext.getSqlParserConfig(PlannerContext.java:237)
	at org.apache.flink.table.planner.delegation.PlannerContext.createFrameworkConfig(PlannerContext.java:142)
	at org.apache.flink.table.planner.delegation.PlannerContext.<init>(PlannerContext.java:124)
	at org.apache.flink.table.planner.delegation.PlannerBase.<init>(PlannerBase.scala:121)
	at org.apache.flink.table.planner.delegation.StreamPlanner.<init>(StreamPlanner.scala:65)
	at org.apache.flink.table.planner.delegation.DefaultPlannerFactory.create(DefaultPlannerFactory.java:65)
	at org.apache.flink.table.factories.PlannerFactoryUtil.createPlanner(PlannerFactoryUtil.java:58)
	at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.create(StreamTableEnvironmentImpl.java:127)
	at org.apache.flink.table.api.bridge.java.StreamTableEnvironment.create(StreamTableEnvironment.java:122)
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:86)
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:69)
	at org.dinky.executor.LocalStreamExecutor.createCustomTableEnvironment(LocalStreamExecutor.java:72)
	at org.dinky.executor.Executor.init(Executor.java:142)
	at org.dinky.executor.LocalStreamExecutor.<init>(LocalStreamExecutor.java:67)
	at org.dinky.executor.ExecutorFactory.buildLocalExecutor(ExecutorFactory.java:52)
	at org.dinky.executor.ExecutorFactory.buildExecutor(ExecutorFactory.java:44)
	at org.dinky.job.JobManager.init(JobManager.java:220)
	at org.dinky.job.JobManager.build(JobManager.java:197)
	at org.dinky.service.task.FlinkSqlTask.getJobManager(FlinkSqlTask.java:72)
	at org.dinky.service.task.FlinkSqlTask.<init>(FlinkSqlTask.java:51)
	... 145 more

Process FlinkSubmit/14 exit with status:FAILED



```

**Comment by Zzm0809** [comment]
认真看下整库同步中到底是 $ 还是 #

**Comment by suiquantong** [comment]
这个问题我知道 ，但是问题不在这里 我试过$和# 都会报这个错误

**Comment by aiwenmo** [comment]
Need to compile dinky in the environment of Flink1.16.

**Comment by suiquantong** [comment]
我目前就是使用1.16.3版本啊

**Comment by aiwenmo** [comment]
You are currently using a distribution package, which compiles dinky in the Flink 1.18 environment.

**Comment by suiquantong** [comment]
那我应该怎么办，自己打包flink 嘛 还是怎么办  这个flink 就是网上下载的  flink-1.16.3-bin-scala_2.12.tgz 文件进行部署的
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        1/26/2024 10:18
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [DataLinkDC/dinky] [Bug] Flink-SQL check backend error (Issue #3067)
        
      
    
  

You are currently using a distribution package, which compiles dinky in the Flink 1.18 environment.

**Comment by aiwenmo** [comment]
mvn clean package -DskipTests=true -P prod,jdk11,flink-single-version,scala-2.12,aliyun,flink-1.16,!dev,!jdk-1.8

**Comment by zackyoungh** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/42713096/86b00f83-d4ca-4e92-b3ad-795cd572d462)
你的依赖看看，flink-table-planner是否真的被加载了，在dinky安装目录下
