### ISSUE TITLE
[Bug] [admin] Sysinit udf NPE

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#3099]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
----------------------------------------------------------
Application 'Dinky' is running! Access URLs:
Local:          http://localhost:8888
External:       http://10.42.0.147:8888
Doc:    http://10.42.0.147:8888/doc.html
Druid Monitor:  http://10.42.0.147:8888/druid/index.html
Actuator:       http://10.42.0.147:8888/actuator
----------------------------------------------------------
[dinky] 2024-01-30 21:41:56.869   INFO    18 --- [           main] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[dinky] 2024-01-30 21:41:56.901  ERROR    18 --- [           main] org.springframework.boot.SpringApplication: Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-2.7.11.jar:2.7.11]
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749) ~[spring-boot-2.7.11.jar:2.7.11]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.11.jar:2.7.11]
at org.dinky.Dinky.main(Dinky.java:47) ~[dinky-admin-1.0.0-rc3.jar:?]
Caused by: java.lang.NullPointerException
at org.dinky.utils.UDFUtils.taskToUDF(UDFUtils.java:32) ~[dinky-admin-1.0.0-rc3.jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
at org.dinky.init.SystemInit.registerUDF(SystemInit.java:225) ~[dinky-admin-1.0.0-rc3.jar:?]
at org.dinky.init.SystemInit.run(SystemInit.java:110) ~[dinky-admin-1.0.0-rc3.jar:?]
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759) ~[spring-boot-2.7.11.jar:2.7.11]
... 3 more
[dinky] 2024-01-30 21:41:56.908   INFO    18 --- [           main] org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: Stopping...
[dinky] 2024-01-30 21:41:56.908   INFO    18 --- [           main] org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@7d2b832]]
[dinky] 2024-01-30 21:41:56.909   INFO    18 --- [           main] org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: Stopped.
[dinky] 2024-01-30 21:41:56.934   WARN    18 --- [    scheduler-1] oshi.util.Util: Interrupted while sleeping for 1000 ms: sleep interrupted
[dinky] 2024-01-30 21:41:56.940   INFO    18 --- [           main] com.alibaba.druid.pool.DruidDataSource: {dataSource-1} closing ...
[dinky] 2024-01-30 21:41:56.945   INFO    18 --- [           main] com.alibaba.druid.pool.DruidDataSource: {dataSource-1} closed
```

### What you expected to happen

npe

### How to reproduce

npe

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
solved
