### ISSUE TITLE
Couldn't deploy Yarn Application Cluster(version 1.0.0.rc4)

### ISSUE THREAD

**Issue by jetliu1711** [DataLinkDC/dinky#3150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I write my flinksql ,choose executor mode is yarn appcation and I also add applicaton jar hdfs:///dinky/lib/flink1.17/dinky-app-1.17-1.0.0-rc4-jar-with-dependencies.jar to the cluster ,then click the running button,so I can't submit the task to the yarn。here are some logs with the question:
2024-02-06 14:13:32,555 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Could not create application program.
org.apache.flink.util.FlinkException: Could not load the provided entrypoint class.
        at org.apache.flink.client.program.DefaultPackagedProgramRetriever.getPackagedProgram(DefaultPackagedProgramRetriever.java:215) ~[flink-dist-1.17.2.jar:1.17.2]
        at org.apache.flink.yarn.entrypoint.YarnApplicationClusterEntryPoint.getPackagedProgram(YarnApplicationClusterEntryPoint.java:126) ~[flink-dist-1.17.2.jar:1.17.2]
        at org.apache.flink.yarn.entrypoint.YarnApplicationClusterEntryPoint.main(YarnApplicationClusterEntryPoint.java:96) [flink-dist-1.17.2.jar:1.17.2]
Caused by: org.apache.flink.client.program.ProgramInvocationException: JAR file does not exist '/data/vdh/yarn/local/usercache/dinky/appcache/application_1707125270554_0010/container_e08_1707125270554_0010_01_000001/dinky-app-1.17-1.0.0-rc4-jar-with-dependencies.jar'
        at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:617) ~[flink-dist-1.17.2.jar:1.17.2]
        at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist-1.17.2.jar:1.17.2]
        at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist-1.17.2.jar:1.17.2]
        at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist-1.17.2.jar:1.17.2]
        at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist-1.17.2.jar:1.17.2]
        at org.apache.flink.client.program.DefaultPackagedProgramRetriever.getPackagedProgram(DefaultPackagedProgramRetriever.java:213) ~[flink-dist-1.17.2.jar:1.17.2]
        ... 2 more

### What you expected to happen

success to the yarn

### How to reproduce

write flinksql task,choose executor mode is yarn appcation then click the running button。

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hugh018** [comment]
复现 flink-1.17.2 dinky-1.0.2
