### ISSUE TITLE
[Bug]Couldn't deploy Yarn Application Cluster

### ISSUE THREAD

**Issue by jetliu1711** [DataLinkDC/dinky#3163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Use application mode sumbit flink sql task，it makes some errors,like this：
2024-02-19 13:24:58,616 WARN  org.apache.flink.configuration.Configuration                 [] - Config uses deprecated configuration key 'web.port' instead of proper key 'rest.bind-port'
2024-02-19 13:24:58,632 INFO  org.apache.flink.runtime.clusterframework.BootstrapTools     [] - Setting directories for temporary files to: /data/vdb/yarn/local/usercache/dinky/appcache/application_1707125270554_0031,/data/vdc/yarn/local/usercache/dinky/appcache/application_1707125270554_0031,/data/vdd/yarn/local/usercache/dinky/appcache/application_1707125270554_0031,/data/vde/yarn/local/usercache/dinky/appcache/application_1707125270554_0031,/data/vdf/yarn/local/usercache/dinky/appcache/application_1707125270554_0031,/data/vdg/yarn/local/usercache/dinky/appcache/application_1707125270554_0031,/data/vdh/yarn/local/usercache/dinky/appcache/application_1707125270554_0031
2024-02-19 13:24:58,668 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Could not create application program.
org.apache.flink.util.FlinkException: Could not load the provided entrypoint class.
	at org.apache.flink.client.program.DefaultPackagedProgramRetriever.getPackagedProgram(DefaultPackagedProgramRetriever.java:215) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.yarn.entrypoint.YarnApplicationClusterEntryPoint.getPackagedProgram(YarnApplicationClusterEntryPoint.java:126) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.yarn.entrypoint.YarnApplicationClusterEntryPoint.main(YarnApplicationClusterEntryPoint.java:96) [flink-dist-1.17.2.jar:1.17.2]
Caused by: org.apache.flink.client.program.ProgramInvocationException: JAR file does not exist '/data/vdb/yarn/local/usercache/dinky/appcache/application_1707125270554_0031/container_e08_1707125270554_0031_01_000001/dinky-app-1.17-1.0.0-rc4-jar-with-dependencies.jar'
	at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:617) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.DefaultPackagedProgramRetriever.getPackagedProgram(DefaultPackagedProgramRetriever.java:213) ~[flink-dist-1.17.2.jar:1.17.2]
	... 2 more
Caused by: java.io.IOException: JAR file does not exist '/data/vdb/yarn/local/usercache/dinky/appcache/application_1707125270554_0031/container_e08_1707125270554_0031_01_000001/dinky-app-1.17-1.0.0-rc4-jar-with-dependencies.jar'
	at org.apache.flink.util.JarUtils.checkJarFile(JarUtils.java:46) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:615) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist-1.17.2.jar:1.17.2]
	at org.apache

### What you expected to happen

can work well

### How to reproduce

write flink sql task ,then click the "running" button.

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@jetliu1711 请规范编写 issue title  否则将视为无效 issue

**Comment by hugh018** [comment]
复现 flink-1.17.2 dinky-1.0.2
