### ISSUE TITLE
[Bug] [admin] ERROR org.apache.juli.logging.DirectJDKLog 175 log

### ISSUE THREAD

**Issue by gitfortian** [DataLinkDC/dinky#3164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

[dinky] 2024-02-19 17:14:44 CST ERROR org.apache.juli.logging.DirectJDKLog 175 log - Exception Processing ErrorPage[errorCode=0, location=/error] java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getHttpServletMapping()Ljavax/servlet/http/HttpServletMapping;
        at org.apache.catalina.core.ApplicationHttpRequest.setRequest(ApplicationHttpRequest.java:681) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.ApplicationHttpRequest.<init>(ApplicationHttpRequest.java:103) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.ApplicationDispatcher.wrapRequest(ApplicationDispatcher.java:857) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:513) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:480) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:354) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:237) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:319) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:237) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_392]

### What you expected to happen

no error log

### How to reproduce

just start server

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Check for dependency conflicts.
