### ISSUE TITLE
An error is reported when you run mysqlcdc2mysql in local mode in flink 1.18

### ISSUE THREAD

**Issue by yangzehan** [DataLinkDC/dinky#3167]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/76773988/d36e29fc-7d61-4378-adc6-aa68de287f2d)
当我使用flink1.18版本local模式调试cdc时报错：
java.lang.NoClassDefFoundError: Could not initialize class org.apache.flink.connector.jdbc.utils.JdbcTypeUtil
	at org.apache.flink.connector.jdbc.converter.AbstractJdbcRowConverter.wrapIntoNullableExternalConverter(AbstractJdbcRowConverter.java:197) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.converter.AbstractJdbcRowConverter.createNullableExternalConverter(AbstractJdbcRowConverter.java:192) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.converter.AbstractJdbcRowConverter.<init>(AbstractJdbcRowConverter.java:69) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.internal.converter.MySQLRowConverter.<init>(MySQLRowConverter.java:38) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.dialect.mysql.MySqlDialect.getRowConverter(MySqlDialect.java:56) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.createSimpleRowExecutor(JdbcOutputFormatBuilder.java:211) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.lambda$createUpsertRowExecutor$3(JdbcOutputFormatBuilder.java:190) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_333]
	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.createUpsertRowExecutor(JdbcOutputFormatBuilder.java:190) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.createBufferReduceExecutor(JdbcOutputFormatBuilder.java:152) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.table.JdbcOutputFormatBuilder.lambda$build$d2919689$1(JdbcOutputFormatBuilder.java:104) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.internal.JdbcOutputFormat.createAndOpenStatementExecutor(JdbcOutputFormat.java:170) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.internal.JdbcOutputFormat.open(JdbcOutputFormat.java:144) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction.open(GenericJdbcSinkFunction.java:52) ~[flink-connector-jdbc-3.1.0-1.17.jar:3.1.0-1.17]
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34) ~[flink-core-1.18.0.jar:1.18.0]
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:101) ~[flink-streaming-java-1.18.0.jar:1.18.0]
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.open(SinkOperator.java:58) ~[flink-table-runtime-1.18.0.jar:1.18.0]
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:107) ~[flink-streaming-java-1.18.0.jar:1.18.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:753) ~[flink-streaming-java-1.18.0.jar:1.18.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55) ~[flink-streaming-java-1.18.0.jar:1.18.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:728) ~[flink-streaming-java-1.18.0.jar:1.18.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:693) ~[flink-streaming-java-1.18.0.jar:1.18.0]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953) ~[flink-runtime-1.18.0.jar:1.18.0]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:922) ~[flink-runtime-1.18.0.jar:1.18.0]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746) ~[flink-runtime-1.18.0.jar:1.18.0]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) ~[flink-runtime-1.18.0.jar:1.18.0]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_333]

原因大概是flink-connector-jdbc3.1.0-1.17版本的JdbcTypeUtil类依赖的shaded.guava版本和当前flink1.18pom文件内的shaded.guava版本对不齐路径
![image](https://github.com/DataLinkDC/dinky/assets/76773988/15c0a088-de1c-4cc3-8908-c1596a2f1693)
尝试更新flink-connector-jdbc版本到3.1.1-1.17可以解决

### What you expected to happen

正常执行mysqlcdc2mysql

### How to reproduce

本地调试dinky使用local模式运行mysqlcdc2mysql

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@yangzehan 请规范你的 issue title, 否则将视为无效 issue
