### ISSUE TITLE
[Bug] [datastudio] Data too long for column 'job_id'(varchar(50)) in table dinky_history

### ISSUE THREAD

**Issue by jiangwwwei** [DataLinkDC/dinky#3196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

after submit a  task on k8s application ,the task status is not associated
(The task ran successfully in practice)
![image](https://github.com/DataLinkDC/dinky/assets/52434907/c61a1d35-669c-4bd6-a345-d0f192cd59b0)
![image](https://github.com/DataLinkDC/dinky/assets/52434907/760576cf-c7b4-48e3-9b31-37e628254d18)
![image](https://github.com/DataLinkDC/dinky/assets/52434907/62c62e1a-2732-4595-8e6c-c309282511c8)

----------------------------------------------
```
error log:
Process Step SUBMIT_EXECUTE exit with status:FAILED
org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'job_id' at row 1
### The error may exist in org/dinky/mapper/HistoryMapper.java (best guess)
### The error may involve org.dinky.mapper.HistoryMapper.updateById-Inline
### The error occurred while setting parameters
### SQL: UPDATE dinky_history SET job_id = ?, job_manager_address = ?, batch_model = ?, status = ?, error = ?, end_time = ? WHERE id = ? AND tenant_id = 1
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'job_id' at row 1
; Data truncation: Data too long for column 'job_id' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'job_id' at row 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy154.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy165.updateById(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.updateById(IService.java:239)
	at com.baomidou.mybatisplus.extension.service.IService$$FastClassBySpringCGLIB$$f8525d18.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at org.dinky.service.impl.HistoryServiceImpl$$EnhancerBySpringCGLIB$$6fa58798.updateById(<generated>)
	at org.dinky.job.handler.Job2MysqlHandler.failed(Job2MysqlHandler.java:220)
	at org.dinky.job.JobManager.failed(JobManager.java:234)
	at org.dinky.job.JobManager.executeSql(JobManager.java:361)
	at org.dinky.service.task.FlinkSqlTask.execute(FlinkSqlTask.java:67)
	at org.dinky.service.impl.TaskServiceImpl.executeJob(TaskServiceImpl.java:189)
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	……
```

----------------------------------------------

### What you expected to happen

The task status is associated normally.

### How to reproduce

dinky version : 1.0.0 rc4
execute mode : k8s application
job_name:  test-long-jobname-12345678902701234567890123
(The length of 'job_name' exceeds 18 characters )

in this dinky version,
job_id = job_name + 32_characters_id,
But the default length limit for the job_id field is only 50 characters.  (varchar(50))

### Anything else

Executing the following SQL can temporarily resolve the issue.

`alter table dinky_history modify job_id varchar(100) null comment 'Job ID';`

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Welcome to pull request to fix it.

**Comment by Zzm0809** [comment]
#3210
