### ISSUE TITLE
[Bug] [dinky-admin] org.dinky.shaded.paimon.codegen.CodeGeneratorImpl cannot be loaded properly in local mode

### ISSUE THREAD

**Issue by sgsdehen** [DataLinkDC/dinky#3354]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

org.dinky.shaded.paimon.codegen.CodeGeneratorImpl 在local模式下不能正常加载,日志会持续抛出如下异常:
[dinky] 2024-04-03 20:27:27 CST ERROR org.dinky.context.MetricsContextHolder 79 lambda$sendAsync$1 - send metrics async error java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.RuntimeException: Found 0 classes implementing org.dinky.shaded.paimon.codegen.CodeGenerator. They are:
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_321]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_321]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643) ~[?:1.8.0_321]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_321]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_321]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_321]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_321]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Found 0 classes implementing org.dinky.shaded.paimon.codegen.CodeGenerator. They are:
	at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:170) ~[dinky-admin-1.0.1-SNAPSHOT.jar:?]
	at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:70) ~[dinky-admin-1.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_321]
	... 5 more
Caused by: java.lang.RuntimeException: Found 0 classes implementing org.dinky.shaded.paimon.codegen.CodeGenerator. They are:

	at org.dinky.shaded.paimon.codegen.CodeGenLoader.getCodeGenerator(CodeGenLoader.java:46) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.codegen.CodeGenUtils.generateRecordComparator(CodeGenUtils.java:57) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.utils.KeyComparatorSupplier.<init>(KeyComparatorSupplier.java:39) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.KeyValueFileStore.<init>(KeyValueFileStore.java:90) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.table.PrimaryKeyFileStoreTable.store(PrimaryKeyFileStoreTable.java:110) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.table.PrimaryKeyFileStoreTable.newWrite(PrimaryKeyFileStoreTable.java:185) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.table.PrimaryKeyFileStoreTable.newWrite(PrimaryKeyFileStoreTable.java:178) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.table.PrimaryKeyFileStoreTable.newWrite(PrimaryKeyFileStoreTable.java:56) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.table.sink.BatchWriteBuilderImpl.newWrite(BatchWriteBuilderImpl.java:61) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:127) ~[dinky-admin-1.0.1-SNAPSHOT.jar:?]
	at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:70) ~[dinky-admin-1.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_321]
	... 5 more

### What you expected to happen

监控数据PaimonUtil.write()正常执行并落盘

### How to reproduce

使用如下sql 执行查询,会触发此bug
CREATE   TABLE source_datagen(
  id BIGINT,
  money BIGINT
) WITH(
  'connector' = 'datagen',
  'rows-per-second' = '1',
  'fields.id.min' = '1',
  'fields.id.max' = '100000',
  'fields.money.min' = '1',
  'fields.money.max' = '100000'
);
 print source_datagen ;

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shuai1998** [comment]
我也遇到了，怎么解决的

**Comment by sgsdehen** [comment]
> 我也遇到了，怎么解决的

https://github.com/DataLinkDC/dinky/pull/3355
