### ISSUE TITLE
[Bug] [spark]cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.flink.streaming.api...

### ISSUE THREAD

**Issue by wangjiancheng180** [DataLinkDC/dinky#3359]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我使用了dinky1.18搭配flink1.8.0，在进行postgresql整库迁移时在本地运行作业时并没有出现这个问题，但是将作业发布运行到flink上时出现了这个问题
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:399)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.getOperatorRecordsOutCounter(OperatorChain.java:646)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.wrapOperatorIntoOutput(OperatorChain.java:896)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:836)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:724)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:817)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:724)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:817)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:724)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:817)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:724)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:202)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.<init>(RegularOperatorChain.java:60)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:707)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:693)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:922)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.userFunction of type org.apache.flink.api.common.functions.Function in instance of org.apache.flink.streaming.api.operators.StreamFlatMap
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2302)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1432)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2460)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2454)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2236)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1692)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:539)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:527)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:481)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:383)
	... 19 more

### What you expected to happen

经过一些搜索我发现很多回答是说spark版本与hudi版本冲突，这个我不知道我该怎么解决。
关于spark版本不都是2.12吗？为什么本地无冲突而到服务器会冲突呢？
还有一些是让我更改flink-conf.yml文件里的classloader-resolve-order: parent-first 我尝试后并没有解决。

### How to reproduce

远程发布整库迁移
以下是我的sql
EXECUTE CDCSOURCE cdc_postgresql WITH (
 'connector' = 'postgres-cdc',
 'hostname' = '****',
 'port' = '5432',
 'username' = 'postgres',
 'password' = '*******',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'latest-offset',
 'database-name' = 'guardian_test_data',
 'schema-name' = 'public',
 'parallelism' = '1',
 'table-name' = 'public\..*',
 'debezium.slot.name' = 'test2',
 'debezium.plugin.name'= 'pgoutput',
 'debezium.snapshot.mode'= 'never',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:postgresql://********/guaridan_test_data',
 'sink.username' = 'postgres',
 'sink.password' = '******',
 'sink.sink.db' = 'guaridan_test_data',
--   'sink.table.prefix' = 'guaridan_test_data_',
 'sink.table.lower' = 'true',
 'sink.table-name' = '#{tableName}',
 'sink.driver' = 'org.postgresql.Driver',
 'sink.sink.buffer-flush.interval' = '2s',
 'sink.sink.buffer-flush.max-rows' = '100',
 'sink.sink.max-retries' = '5'
)

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
添加 dinky-app 包到 flink/lib or hdfs 的 flink/lib and 添加到 dinky/extends/flink${version}/

**Comment by shenyi0828** [comment]
dinky-app-${flink_version}-${dinky_version}-jar-with-dependencies 直接加入  ${FLINK_HOME}/lib/ 下会可能有 guava 冲突。

dinky 的 guava 版本高，如果用 flink-s3-fs-presto-${flink_version}.jar ，依赖的 com.facebook.presto 用到了一个 guava 32 以下才有的函数。需要把 dinky-app.jar 拆了，删掉 com.google.common 文件夹的下的再重新打包。
