### ISSUE TITLE
dinky mysql full database synchronization error

### ISSUE THREAD

**Issue by Hello-Linux** [DataLinkDC/dinky#3445]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

你好，我使用dinky最新版1.0.0 flink版本1.16.3，配置以及依赖lib包都配置好了，但是启动flink任务的时候发现目标库只有表结构同步过来了，表的数据没有同步过来，并且作业日志exception里面有报错日志
```
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:399)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperator(OperatorChain.java:763)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:736)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:676)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:726)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:676)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:726)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:676)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:195)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.<init>(RegularOperatorChain.java:60)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:685)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:672)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:904)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.userFunction of type org.apache.flink.api.common.functions.Function in instance of org.apache.flink.streaming.api.operators.StreamFlatMap
	at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(Unknown Source)
	at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(Unknown Source)
	at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(Unknown Source)
	at java.base/java.io.ObjectInputStream.defaultCheckFieldValues(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:617)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:602)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:589)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:543)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:383)
	... 16 more

```

### What you expected to happen

表数据同步成功

### How to reproduce

安装flink1.16.3 flink，后使用docker 部署dinky1.0.0-rc3，把相关的flink cdc lib包拷贝到各自目录下，启动任务后报错

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hello-Linux** [comment]
任务一直在重启中
<img width="939" alt="001" src="https://github.com/DataLinkDC/dinky/assets/17851645/b4fd234e-26d0-4dae-8077-e98337b0a536">
我的flink sql语句为
```
EXECUTE CDCSOURCE cdc_mysql WITH (
 'connector' = 'mysql-cdc',
 'hostname' = '192.168.98.199',
 'port' = '3307',
 'username' = 'flink',
 'password' = 'buzhidao',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'database-name' = 'sn_metrics',
 'table-name' = 'sn_metrics\..*',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:mysql://192.168.98.167:3307/sn_metrics?characterEncoding=utf-8&useSSL=false',
 'sink.username' = 'root',
 'sink.password' = 'buzhidao',
 'sink.sink.db' = 'sn_metrics',
 'sink.table.lower' = 'true',
 'sink.table-name' = '#{tableName}',
 'sink.driver' = 'com.mysql.jdbc.Driver',
 'sink.sink.buffer-flush.interval' = '2s',
 'sink.sink.buffer-flush.max-rows' = '100',
 'sink.sink.max-retries' = '5',
 'sink.auto.create' = 'true'
)

```

**Comment by Zzm0809** [comment]
搜索 issue 列表 有解决方案

**Comment by Hello-Linux** [comment]
@Zzm0809  好的我搜索一下

**Comment by Hello-Linux** [comment]
@Zzm0809  你好我按照https://github.com/DataLinkDC/dinky/issues/3299，这个尝试了把dinky-app-1.16-1.0.0-rc3-jar-with-dependencies.jar放到了/opt/dinky/extends目录下还是报这个错误，为啥呢？

**Comment by Hello-Linux** [comment]
<img width="974" alt="001" src="https://github.com/DataLinkDC/dinky/assets/17851645/b8d5f92d-fe30-42ea-833b-7cf90aa2df25">
<img width="389" alt="002" src="https://github.com/DataLinkDC/dinky/assets/17851645/b33f4b74-5702-4677-8c89-63a7ef3fec70">
<img width="427" alt="003" src="https://github.com/DataLinkDC/dinky/assets/17851645/0d0efb1b-d50c-43a3-9e2a-e71f6e0ecf60">

**Comment by Hello-Linux** [comment]
@aiwenmo

**Comment by Hello-Linux** [comment]
现在貌似也出现了这个报错
**jobManager**
```
jobmanager-1  | org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: MySQL CDC Source -> Map -> Process -> (Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map)' (operator cbc357ccb763df2852fee8c4fc7d55f2).
jobmanager-1  |         at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:617) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$QuiesceableContext.failJob(RecreateOnResetOperatorCoordinator.java:242) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.failJob(SourceCoordinatorContext.java:394) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:221) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$DeferrableCoordinator.resetAndStart(RecreateOnResetOperatorCoordinator.java:410) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator.lambda$resetToCheckpoint$7(RecreateOnResetOperatorCoordinator.java:155) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
jobmanager-1  |         at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
jobmanager-1  |         at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
jobmanager-1  |         at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
jobmanager-1  |         at org.apache.flink.runtime.operators.coordination.ComponentClosingUtils.lambda$closeAsyncWithTimeout$0(ComponentClosingUtils.java:77) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         at java.lang.Thread.run(Unknown Source) ~[?:?]
jobmanager-1  | Caused by: java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig
jobmanager-1  |         at com.ververica.cdc.connectors.mysql.source.connection.PooledDataSourceFactory.createPooledDataSource(PooledDataSourceFactory.java:39) ~[flink-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionPools.getOrCreateConnectionPool(JdbcConnectionPools.java:49) ~[flink-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at com.ververica.cdc.connectors.mysql.source.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:54) ~[flink-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:888) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:883) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:411) ~[flink-sql-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:68) ~[flink-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at com.ververica.cdc.connectors.mysql.MySqlValidator.createJdbcConnection(MySqlValidator.java:83) ~[flink-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at com.ververica.cdc.connectors.mysql.MySqlValidator.validate(MySqlValidator.java:68) ~[flink-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at com.ververica.cdc.connectors.mysql.source.MySqlSource.createEnumerator(MySqlSource.java:197) ~[flink-connector-mysql-cdc-3.0.0.jar:3.0.0]
jobmanager-1  |         at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:217) ~[flink-dist-1.16.3.jar:1.16.3]
jobmanager-1  |         ... 8 more
```
