### ISSUE TITLE
[Bug]  Could not parse value '1000m' for key 'kubernetes.jobmanager.cpu.amount'

### ISSUE THREAD

**Issue by charnet1019** [DataLinkDC/dinky#3514]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Config JM and TM CPU in the k8s application mode with 1000m

![image](https://github.com/DataLinkDC/dinky/assets/18616254/9c0d35a3-f615-433e-ad3d-091c21a48416)

```bash
Caused by: java.lang.IllegalArgumentException: Could not parse value '1000m' for key 'kubernetes.jobmanager.cpu.amount'.
	at org.apache.flink.configuration.Configuration.getOptional(Configuration.java:736) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.configuration.Configuration.getDouble(Configuration.java:472) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.parameters.KubernetesJobManagerParameters.getJobManagerCPU(KubernetesJobManagerParameters.java:125) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateMainContainer(InitJobManagerDecorator.java:143) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateFlinkPod(InitJobManagerDecorator.java:109) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.factory.KubernetesJobManagerFactory.buildKubernetesJobManagerSpecification(KubernetesJobManagerFactory.java:93) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployClusterInternal(KubernetesClusterDescriptor.java:250) ~[dinky-client-1.18-1.0.2.jar:?]
	at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployApplicationCluster(KubernetesClusterDescriptor.java:199) ~[dinky-client-1.18-1.0.2.jar:?]
	at org.dinky.gateway.kubernetes.KubernetesApplicationGateway.deployApplication(KubernetesApplicationGateway.java:153) ~[dinky-gateway-1.0.2.jar:?]
	at org.dinky.gateway.kubernetes.KubernetesApplicationGateway.submitJar(KubernetesApplicationGateway.java:86) ~[dinky-gateway-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.submitByGateway(JobTransBuilder.java:193) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.processWithGateway(JobTransBuilder.java:109) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.handleStatementSet(JobTransBuilder.java:81) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.run(JobTransBuilder.java:70) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.JobManager.executeSql(JobManager.java:361) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.service.task.FlinkSqlTask.execute(FlinkSqlTask.java:68) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl.executeJob(TaskServiceImpl.java:191) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.2.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.aop.ProcessAspect.processStepAround(ProcessAspect.java:110) ~[dinky-admin-1.0.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$43302e2b.executeJob(<generated>) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl.submitTask(TaskServiceImpl.java:319) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.2.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.0.2.jar:?]
	... 108 more
Caused by: java.lang.NumberFormatException: For input string: "1000m"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:543) ~[?:?]
	at org.apache.flink.configuration.ConfigurationUtils.convertToDouble(ConfigurationUtils.java:513) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.configuration.ConfigurationUtils.convertValue(ConfigurationUtils.java:325) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.configuration.Configuration.lambda$getOptional$3(Configuration.java:730) ~[flink-dist-1.18.1.jar:1.18.1]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at org.apache.flink.configuration.Configuration.getOptional(Configuration.java:730) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.configuration.Configuration.getDouble(Configuration.java:472) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.parameters.KubernetesJobManagerParameters.getJobManagerCPU(KubernetesJobManagerParameters.java:125) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateMainContainer(InitJobManagerDecorator.java:143) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.decorators.InitJobManagerDecorator.decorateFlinkPod(InitJobManagerDecorator.java:109) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.kubeclient.factory.KubernetesJobManagerFactory.buildKubernetesJobManagerSpecification(KubernetesJobManagerFactory.java:93) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployClusterInternal(KubernetesClusterDescriptor.java:250) ~[dinky-client-1.18-1.0.2.jar:?]
	at org.apache.flink.kubernetes.KubernetesClusterDescriptor.deployApplicationCluster(KubernetesClusterDescriptor.java:199) ~[dinky-client-1.18-1.0.2.jar:?]
	at org.dinky.gateway.kubernetes.KubernetesApplicationGateway.deployApplication(KubernetesApplicationGateway.java:153) ~[dinky-gateway-1.0.2.jar:?]
	at org.dinky.gateway.kubernetes.KubernetesApplicationGateway.submitJar(KubernetesApplicationGateway.java:86) ~[dinky-gateway-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.submitByGateway(JobTransBuilder.java:193) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.processWithGateway(JobTransBuilder.java:109) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.handleStatementSet(JobTransBuilder.java:81) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.builder.JobTransBuilder.run(JobTransBuilder.java:70) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.job.JobManager.executeSql(JobManager.java:361) ~[dinky-core-1.0.2.jar:?]
	at org.dinky.service.task.FlinkSqlTask.execute(FlinkSqlTask.java:68) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl.executeJob(TaskServiceImpl.java:191) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.2.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.aop.ProcessAspect.processStepAround(ProcessAspect.java:110) ~[dinky-admin-1.0.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$43302e2b.executeJob(<generated>) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl.submitTask(TaskServiceImpl.java:319) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.2.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.0.2.jar:?]
	... 108 more
```

Official docs:
![image](https://github.com/DataLinkDC/dinky/assets/18616254/709d57d6-b116-48d9-a359-87430393114f)

### What you expected to happen

work fine.

### How to reproduce

Config JM and TM CPU in the k8s application mode with 1000m then run a flink job.

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
去掉 m

**Comment by charnet1019** [comment]
Ok.
