### ISSUE TITLE
[Bug]ava.lang.IllegalArgumentException: newLimit > capacity: (88 > 81)

### ISSUE THREAD

**Issue by Wang112233www** [DataLinkDC/dinky#3529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.0.2和1.0.1版本，执行都有如下报错日志：
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: newLimit > capacity: (88 > 81)
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:170) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]

### What you expected to happen

1.0.2和1.0.1版本，执行都有如下报错日志：
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: newLimit > capacity: (88 > 81)
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:170) ~[dinky-admin-1.0.1.jar:?]

### How to reproduce

1.0.2和1.0.1版本，执行都有如下报错日志：
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: newLimit > capacity: (88 > 81)
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:170) ~[dinky-admin-1.0.1.jar:?]

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Wang112233www** [comment]
用的是PG做配置库

**Comment by Wang112233www** [comment]
at org.dinky.shaded.paimon.table.sink.TableWriteImpl.prepareCommit(TableWriteImpl.java:174) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.prepareCommit(TableWriteImpl.java:181) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:162) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]

**Comment by Zzm0809** [comment]
以移除 paimon 作为监控数据存储介质, 此 issue 关闭
