### ISSUE TITLE
[FAQ] No content to map due to end-of-input

### ISSUE THREAD

**Issue by lucky-lbc** [DataLinkDC/dinky#3548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

version: dinky-release-1.17-1.0.1
i change the mysql config yml 
and use  ./auto.sh start to start dinky application
the error about jackson , i dont`t  know why . is mysql database data question?

### What you expected to happen

i want to know what happend and how to solved it

### How to reproduce

![Uploading 图片.png…]()

### Anything else

[dinky] 2024-05-31 10:47:25 CST INFO  org.dinky.context.EngineContextHolder 68 lambda$loadExpressionVariableClass$1 - load class : cn.hutool.core.date.DateUtil
[dinky] 2024-05-31 10:47:25 CST INFO  org.dinky.context.EngineContextHolder 68 lambda$loadExpressionVariableClass$1 - load class : cn.hutool.core.util.IdUtil
[dinky] 2024-05-31 10:47:25 CST INFO  org.dinky.context.EngineContextHolder 68 lambda$loadExpressionVariableClass$1 - load class : cn.hutool.core.util.RandomUtil
[dinky] 2024-05-31 10:47:25 CST INFO  org.dinky.context.EngineContextHolder 68 lambda$loadExpressionVariableClass$1 - load class : cn.hutool.core.util.StrUtil
[dinky] 2024-05-31 10:47:39 CST WARN  org.dinky.shaded.paimon.utils.HadoopUtils 125 getHadoopConfiguration - Could not find Hadoop configuration via any of the supported methods
[dinky] 2024-05-31 10:47:42 CST ERROR org.dinky.context.MetricsContextHolder 71 lambda$sendAsync$1 - send metrics async error java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.UncheckedIOException: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_402]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_402]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643) ~[?:1.8.0_402]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_402]
Caused by: java.lang.RuntimeException: java.io.UncheckedIOException: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:170) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_402]
        ... 1 more
Caused by: java.io.UncheckedIOException: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at org.dinky.shaded.paimon.utils.JsonSerdeUtil.fromJson(JsonSerdeUtil.java:127) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromJson(Snapshot.java:414) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromPath(Snapshot.java:420) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.utils.SnapshotManager.snapshot(SnapshotManager.java:84) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreScan.withSnapshot(AbstractFileStoreScan.java:160) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.scanExistingFileMetas(AbstractFileStoreWrite.java:396) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.createWriterContainer(AbstractFileStoreWrite.java:341) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.lambda$getWriterWrapper$2(AbstractFileStoreWrite.java:328) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1128) ~[?:1.8.0_402]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.getWriterWrapper(AbstractFileStoreWrite.java:327) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:126) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:119) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.write(TableWriteImpl.java:114) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:159) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_402]
        ... 1 more
Caused by: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2095) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1546) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.utils.JsonSerdeUtil.fromJson(JsonSerdeUtil.java:125) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromJson(Snapshot.java:414) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromPath(Snapshot.java:420) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.utils.SnapshotManager.snapshot(SnapshotManager.java:84) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreScan.withSnapshot(AbstractFileStoreScan.java:160) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.scanExistingFileMetas(AbstractFileStoreWrite.java:396) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.createWriterContainer(AbstractFileStoreWrite.java:341) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.lambda$getWriterWrapper$2(AbstractFileStoreWrite.java:328) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1128) ~[?:1.8.0_402]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.getWriterWrapper(AbstractFileStoreWrite.java:327) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:126) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:119) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.write(TableWriteImpl.java:114) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:159) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_402]
        ... 1 more

[dinky] 2024-05-31 10:47:43 CST ERROR org.dinky.context.MetricsContextHolder 71 lambda$sendAsync$1 - send metrics async error java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.UncheckedIOException: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_402]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_402]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643) ~[?:1.8.0_402]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_402]
Caused by: java.lang.RuntimeException: java.io.UncheckedIOException: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:170) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_402]
        ... 1 more
Caused by: java.io.UncheckedIOException: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at org.dinky.shaded.paimon.utils.JsonSerdeUtil.fromJson(JsonSerdeUtil.java:127) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromJson(Snapshot.java:414) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromPath(Snapshot.java:420) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.utils.SnapshotManager.snapshot(SnapshotManager.java:84) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreScan.withSnapshot(AbstractFileStoreScan.java:160) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.scanExistingFileMetas(AbstractFileStoreWrite.java:396) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.createWriterContainer(AbstractFileStoreWrite.java:341) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.lambda$getWriterWrapper$2(AbstractFileStoreWrite.java:328) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1128) ~[?:1.8.0_402]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.getWriterWrapper(AbstractFileStoreWrite.java:327) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:126) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:119) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.write(TableWriteImpl.java:114) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:159) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_402]
        ... 1 more
Caused by: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2095) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1546) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.utils.JsonSerdeUtil.fromJson(JsonSerdeUtil.java:125) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromJson(Snapshot.java:414) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.Snapshot.fromPath(Snapshot.java:420) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.utils.SnapshotManager.snapshot(SnapshotManager.java:84) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreScan.withSnapshot(AbstractFileStoreScan.java:160) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.scanExistingFileMetas(AbstractFileStoreWrite.java:396) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.createWriterContainer(AbstractFileStoreWrite.java:341) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.lambda$getWriterWrapper$2(AbstractFileStoreWrite.java:328) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1128) ~[?:1.8.0_402]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.getWriterWrapper(AbstractFileStoreWrite.java:327) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:126) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:119) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.shaded.paimon.table.sink.TableWriteImpl.write(TableWriteImpl.java:114) ~[dinky-shaded-paimon-1.0.1.jar:?]
        at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:159) ~[dinky-admin-1.0.1.jar:?]
        at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:62) ~[dinky-admin-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_402]
        ... 1 more

### Version

1.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lucky-lbc** [comment]
i carefully read the log . and found that
is dinky-admin module.   MetricsContextHolder.java                            
this code:   PaimonUtil.write(PaimonTableConstant.DINKY_METRICS, metricsVOS, MetricsVO.class);
but i dont't know why.

**Comment by gaoyan1998** [comment]
> i carefully read the log . and found that is dinky-admin module. MetricsContextHolder.java this code: PaimonUtil.write(PaimonTableConstant.DINKY_METRICS, metricsVOS, MetricsVO.class); but i dont't know why.

Delete the tmp directory under the dinky directory and restart dinky to solve the problem. This is a known problem and will be fixed later.
