### ISSUE TITLE
[Bug] Data is written to paimon

### ISSUE THREAD

**Issue by dubu007** [DataLinkDC/dinky#3766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![企业微信截图_17250924407957](https://github.com/user-attachments/assets/2bbac277-defa-4053-ab9f-977d22197122)
dinky 1.0.2 ,  flink1.18.1  paimon0.8  从kakfa 同步数据到paimon

Caused by: org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2095) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1546) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.shade.jackson2.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1566) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.utils.JsonSerdeUtil.fromJson(JsonSerdeUtil.java:125) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.Snapshot.fromJson(Snapshot.java:414) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.Snapshot.fromPath(Snapshot.java:420) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.utils.SnapshotManager.snapshot(SnapshotManager.java:84) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.operation.AbstractFileStoreScan.withSnapshot(AbstractFileStoreScan.java:160) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.scanExistingFileMetas(AbstractFileStoreWrite.java:396) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.createWriterContainer(AbstractFileStoreWrite.java:341) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.lambda$getWriterWrapper$2(AbstractFileStoreWrite.java:328) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_221]
	at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.getWriterWrapper(AbstractFileStoreWrite.java:327) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:126) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:119) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.shaded.paimon.table.sink.TableWriteImpl.write(TableWriteImpl.java:114) ~[dinky-shaded-paimon-1.0.1.jar:?]
	at org.dinky.utils.PaimonUtil.write(PaimonUtil.java:159) ~[dinky-admin-1.0.2.jar:?]
	at org.dinky.context.MetricsContextHolder.lambda$sendAsync$0(MetricsContextHolder.java:63) ~[dinky-admin-1.0.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_221]
	... 5 more

### What you expected to happen

..

### How to reproduce

..

### Anything else

..

### Version

1.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please upgrade into v1.1.0.
