### ISSUE TITLE
[Bug] [Module Name] Null pointer exception occurs when dinky configures DingTalk alarm

### ISSUE THREAD

**Issue by sprybee** [DataLinkDC/dinky#3793]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我配置钉钉告警后台出现NPE

![image](https://github.com/user-attachments/assets/76ce8b9c-459c-4044-b32f-50044823636f)
![image](https://github.com/user-attachments/assets/dd5f19f1-d4b8-4f55-8ac0-838726d7d4ef)
![image](https://github.com/user-attachments/assets/0d78ef0d-bc8c-46a2-a822-78bd18c4d541)
![image](https://github.com/user-attachments/assets/711bd3e2-fd38-4503-ae1b-c094ec7496ea)

### What you expected to happen

[dinky] 2024-09-09 21:34:02 CST ERROR org.jeasy.rules.core.DefaultRulesEngine 120 doFire - Rule '作业运行异常' performed with error java.lang.NullPointerException: null
        at org.dinky.job.handler.JobAlertHandler.executeAlertAction(JobAlertHandler.java:255) ~[dinky-admin-1.1.0.jar:?]
        at org.dinky.job.handler.JobAlertHandler.lambda$buildRule$5(JobAlertHandler.java:214) ~[dinky-admin-1.1.0.jar:?]
        at org.jeasy.rules.core.DefaultRule.execute(DefaultRule.java:51) ~[easy-rules-core-4.1.0.jar:?]
        at org.jeasy.rules.core.DefaultRulesEngine.doFire(DefaultRulesEngine.java:112) ~[easy-rules-core-4.1.0.jar:?]
        at org.jeasy.rules.core.DefaultRulesEngine.fire(DefaultRulesEngine.java:70) ~[easy-rules-core-4.1.0.jar:?]
        at org.dinky.job.handler.JobAlertHandler.check(JobAlertHandler.java:173) ~[dinky-admin-1.1.0.jar:?]
        at org.dinky.job.FlinkJobTask.dealTask(FlinkJobTask.java:106) ~[dinky-admin-1.1.0.jar:?]
        at org.dinky.daemon.entity.TaskWorker.run(TaskWorker.java:57) ~[dinky-daemon-1.1.0.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]

### How to reproduce

无需复现

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
请给出完整日志, 给出完整复现流程

**Comment by sprybee** [comment]
重装系统，配置如上图告警逻辑，开启任务无告警发出。

**Comment by gaoyan1998** [comment]
> 重装系统，配置如上图告警逻辑，开启任务无告警发出。

这是一个BUG，临时解决方案把责任人和维护人都填写一个就可以了
