### ISSUE TITLE
dinky1.2 flink1.5X problem

### ISSUE THREAD

**Issue by bigdataliuchuang** [DataLinkDC/dinky#4058]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: java.lang.RuntimeException: Unsupported parser type for getCalciteParserSupplier: org.apache.flink.table.planner.delegation.ParserImpl
	at org.dinky.parser.CustomParserImpl.getCalciteParserSupplier(CustomParserImpl.java:57) ~[dinky-client-base-1.2.0-rc5.jar:?]
	at org.dinky.parser.CustomParserImpl.<init>(CustomParserImpl.java:47) ~[dinky-client-base-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.<init>(CustomTableEnvironmentImpl.java:128) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:185) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:134) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.LocalStreamExecutor.createCustomTableEnvironment(LocalStreamExecutor.java:72) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.Executor.init(Executor.java:180) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.LocalStreamExecutor.<init>(LocalStreamExecutor.java:67) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.ExecutorFactory.buildLocalExecutor(ExecutorFactory.java:52) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.ExecutorFactory.buildExecutor(ExecutorFactory.java:44) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.job.JobManager.init(JobManager.java:217) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.job.JobManager.buildPlanMode(JobManager.java:201) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl.lambda$getJobManager$2b450759$1(StudioServiceImpl.java:215) ~[dinky-admin-1.2.0-rc5.jar:?]
	at cn.hutool.core.lang.func.Func0.callWithRuntimeException(Func0.java:36) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:137) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:120) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.Cache.get(Cache.java:78) ~[hutool-all-5.8.31.jar:5.8.31]
	at org.dinky.service.impl.StudioServiceImpl.getJobManager(StudioServiceImpl.java:213) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl.getMSCatalogs(StudioServiceImpl.java:157) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl$$FastClassBySpringCGLIB$$2cea1b8b.invoke(<generated>) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.2.0-rc5.jar:?]
	... 111 more

### What you expected to happen

解决

### How to reproduce

Caused by: java.lang.RuntimeException: Unsupported parser type for getCalciteParserSupplier: org.apache.flink.table.planner.delegation.ParserImpl
	at org.dinky.parser.CustomParserImpl.getCalciteParserSupplier(CustomParserImpl.java:57) ~[dinky-client-base-1.2.0-rc5.jar:?]
	at org.dinky.parser.CustomParserImpl.<init>(CustomParserImpl.java:47) ~[dinky-client-base-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.<init>(CustomTableEnvironmentImpl.java:128) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:185) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:134) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.LocalStreamExecutor.createCustomTableEnvironment(LocalStreamExecutor.java:72) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.Executor.init(Executor.java:180) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.LocalStreamExecutor.<init>(LocalStreamExecutor.java:67) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.ExecutorFactory.buildLocalExecutor(ExecutorFactory.java:52) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.ExecutorFactory.buildExecutor(ExecutorFactory.java:44) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.job.JobManager.init(JobManager.java:217) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.job.JobManager.buildPlanMode(JobManager.java:201) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl.lambda$getJobManager$2b450759$1(StudioServiceImpl.java:215) ~[dinky-admin-1.2.0-rc5.jar:?]
	at cn.hutool.core.lang.func.Func0.callWithRuntimeException(Func0.java:36) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:137) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:120) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.Cache.get(Cache.java:78) ~[hutool-all-5.8.31.jar:5.8.31]
	at org.dinky.service.impl.StudioServiceImpl.getJobManager(StudioServiceImpl.java:213) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl.getMSCatalogs(StudioServiceImpl.java:157) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl$$FastClassBySpringCGLIB$$2cea1b8b.invoke(<generated>) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.2.0-rc5.jar:?]
	... 111 more

### Anything else

Caused by: java.lang.RuntimeException: Unsupported parser type for getCalciteParserSupplier: org.apache.flink.table.planner.delegation.ParserImpl
	at org.dinky.parser.CustomParserImpl.getCalciteParserSupplier(CustomParserImpl.java:57) ~[dinky-client-base-1.2.0-rc5.jar:?]
	at org.dinky.parser.CustomParserImpl.<init>(CustomParserImpl.java:47) ~[dinky-client-base-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.<init>(CustomTableEnvironmentImpl.java:128) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:185) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:134) ~[dinky-client-1.15-1.2.0-rc5.jar:?]
	at org.dinky.executor.LocalStreamExecutor.createCustomTableEnvironment(LocalStreamExecutor.java:72) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.Executor.init(Executor.java:180) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.LocalStreamExecutor.<init>(LocalStreamExecutor.java:67) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.ExecutorFactory.buildLocalExecutor(ExecutorFactory.java:52) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.executor.ExecutorFactory.buildExecutor(ExecutorFactory.java:44) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.job.JobManager.init(JobManager.java:217) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.job.JobManager.buildPlanMode(JobManager.java:201) ~[dinky-core-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl.lambda$getJobManager$2b450759$1(StudioServiceImpl.java:215) ~[dinky-admin-1.2.0-rc5.jar:?]
	at cn.hutool.core.lang.func.Func0.callWithRuntimeException(Func0.java:36) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:137) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.impl.AbstractCache.get(AbstractCache.java:120) ~[hutool-all-5.8.31.jar:5.8.31]
	at cn.hutool.cache.Cache.get(Cache.java:78) ~[hutool-all-5.8.31.jar:5.8.31]
	at org.dinky.service.impl.StudioServiceImpl.getJobManager(StudioServiceImpl.java:213) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl.getMSCatalogs(StudioServiceImpl.java:157) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.dinky.service.impl.StudioServiceImpl$$FastClassBySpringCGLIB$$2cea1b8b.invoke(<generated>) ~[dinky-admin-1.2.0-rc5.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.31.jar:5.3.31]
	at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.2.0-rc5.jar:?]
	... 111 more

### Version

1.2.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by naah69** [comment]
we had the same problem

**Comment by naah69** [comment]
已解决：要配置这个
![image](https://github.com/user-attachments/assets/0f3b8139-8c67-49d0-9de4-48c2e8aacea2)

**Comment by aiwenmo** [comment]
Starting from Flink 1.15, the distribution contains two planners:

- flink-table-planner_2.12-1.20.0.jar, in /opt, contains the query planner
- flink-table-planner-loader-1.20.0.jar, loaded by default in /lib, contains the query planner hidden behind an isolated classpath (you won’t be able to address any io.apache.flink.table.planner directly)
The two planner JARs contain the same code, but they are packaged differently. In the first case, you must use the same Scala version of the JAR. In second case, you do not need to make considerations about Scala, since it is hidden inside the JAR.

By default,flink-table-planner-loader is used by the distribution. If you need to access and use the internals of the query planner, you can swap the JARs (copying and pasting flink-table-planner_2.12.jar in the distribution /lib folder). Be aware that you will be constrained to using the Scala version of the Flink distribution that you are using.
