### ISSUE TITLE
[Bug] [Module Name] Bug Global configuration resource configuration oss storage mode bug

### ISSUE THREAD

**Issue by goldbridge18** [DataLinkDC/dinky#4066]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

从local选择oss 造成 dinky挂掉
![image](https://github.com/user-attachments/assets/af688192-1506-4078-9731-eae0211b3cbe)

dinky] 2024-12-19 10:34:07 CST INFO  org.apache.flink.runtime.webmonitor.history.HistoryServer 291 start - Using directory /opt/dinky-release-1.17-1.2.0/tmp/flink-job-archive as local cache.
[dinky] 2024-12-19 10:34:08 CST ERROR org.apache.flink.util.FatalExitExceptionHandler 43 uncaughtException - FATAL: Thread 'Flink-HistoryServer-ArchiveFetcher-thread-1' produced an uncaught exception. Stopping the process... java.lang.NoClassDefFoundError: org/apache/flink/fs/s3presto/S3FileSystemFactory
        at org.dinky.resource.impl.OssResourceManager.getFileSystem(OssResourceManager.java:152) ~[dinky-client-base-1.2.0.jar:?]
        at org.dinky.url.ResourceFileSystem.listStatus(ResourceFileSystem.java:99) ~[dinky-client-base-1.2.0.jar:?]
        at org.apache.flink.runtime.webmonitor.history.HistoryServerArchiveFetcher.listArchives(HistoryServerArchiveFetcher.java:239) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.webmonitor.history.HistoryServerArchiveFetcher.fetchArchives(HistoryServerArchiveFetcher.java:170) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.webmonitor.history.HistoryServer.lambda$getArchiveFetchingRunnable$3(HistoryServer.java:329) ~[flink-dist-1.17.1.jar:1.17.1]
        at org.apache.flink.runtime.util.Runnables.lambda$withUncaughtExceptionHandler$0(Runnables.java:49) ~[flink-dist-1.17.1.jar:1.17.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_372]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_372]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_372]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_372]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
Caused by: java.lang.ClassNotFoundException: org.apache.flink.fs.s3presto.S3FileSystemFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_372]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_372]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
        ... 13 more

### What you expected to happen

应该是缺少oss包

### How to reproduce

缺少： org/apache/flink/fs/s3presto/S3FileSystemFactory

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你需要集成这个就需要自行加包
将 flink/opt/flink-s3-fs-presto 包拷贝到 dinky/extends/flink${version}/

**Comment by 8Sign24** [comment]
![Image](https://github.com/user-attachments/assets/e19b13a9-381d-487e-8249-8adb9d0ae708)
将 flink/opt/flink-s3-fs-presto 包拷贝到 dinky/extends/flink${version}/ 后，dinky重启加载了 这个包，但是当修改存储模式 为OSS时仍然会报这个错，dinky版本：1.2.3-1.20
Caused by: java.lang.NoSuchMethodError: org.apache.flink.fs.s3.common.AbstractS3FileSystemFactory.<init>(Ljava/lang/String;Lorg/apache/flink/fs/s3presto/common/HadoopConfigLoader;)V

**Comment by 51anygo** [comment]
复制了jar包到目录，重启没用， 还是一直报错， 只能改数据库重启才有用， UPDATE dinky_sys_config SET value='LOCAL' WHERE name='sys.resource.settings.base.model';

**Comment by boerzi** [comment]
> 复制了jar包到目录，重启没用， 还是一直报错， 只能改数据库重启才有用， UPDATE dinky_sys_config SET value='LOCAL' WHERE name='sys.resource.settings.base.model';

感谢，本来想自己去写Update的到这里查到了，这里确实是大坑。
