### ISSUE TITLE
org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor

### ISSUE THREAD

**Issue by ghost** [DataLinkDC/dinky#945]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

java.util.concurrent.CompletionException: org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.lambda$invokeRpc$1(AkkaInvocationHandler.java:251)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.apache.flink.util.concurrent.FutureUtils.doForward(FutureUtils.java:1387)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$null$1(ClassLoadingUtils.java:93)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$guardCompletionWithContextClassLoader$2(ClassLoadingUtils.java:92)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$1.onComplete(AkkaFutureUtils.java:45)
	at akka.dispatch.OnComplete.internal(Future.scala:299)
	at akka.dispatch.OnComplete.internal(Future.scala:297)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:224)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:221)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$DirectExecutionContext.execute(AkkaFutureUtils.java:65)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:621)
	at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:25)
	at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:23)
	at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:532)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor.

### What you expected to happen

Have no clue

### How to reproduce

dlink-0.6.6
yarn-application
flink-1.14.4
dlink-client-hadoop.jar替代 uber包

web ui无日志，hdfs有jobmanager日志，job会挂掉；
如果将log4j.properties放入flink/conf或者添加参数$internal.deployment.config-dir和$internal.yarn.log-config-file，web ui无日志，hdfs也没jobmanager日志详情，仅有“任务提交成功”，job会挂掉

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
尝试把所有的flink配置文件都放在指定的 flink-conf 目录下

**Comment by ghost** [comment]
> 尝试把所有的flink配置文件都放在指定的 flink-conf 目录下

我尝试了，未能解决问题，并且dlink.log显示：
cn.hutool.http.HttpException: Read timed out
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:377)
	at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:350)
	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:64)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:942)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:901)
	at cn.hutool.http.HttpUtil.get(HttpUtil.java:113)
	at com.dlink.api.FlinkAPI.get(FlinkAPI.java:67)
	at com.dlink.api.FlinkAPI.getJobInfo(FlinkAPI.java:183)
	at com.dlink.service.impl.JobHistoryServiceImpl.refreshJobHistory(JobHistoryServiceImpl.java:95)
	at com.dlink.service.impl.JobHistoryServiceImpl$$FastClassBySpringCGLIB$$209718a6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.dlink.service.impl.JobHistoryServiceImpl$$EnhancerBySpringCGLIB$$2c72c5d0.refreshJobHistory(<generated>)
	at com.dlink.service.impl.TaskServiceImpl.refreshJobInstance(TaskServiceImpl.java:752)
	at com.dlink.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$168bea78.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.dlink.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$76f1ee86.refreshJobInstance(<generated>)
	at com.dlink.job.FlinkJobTask.dealTask(FlinkJobTask.java:75)
	at com.dlink.daemon.entity.TaskWorker.run(TaskWorker.java:45)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out

**Comment by aiwenmo** [comment]
报错变了，现在是访问 jobmanager 超时。

**Comment by ynzzxc** [comment]
> 报错变了，现在是访问 jobmanager 超时。

我换uber包了，任务能正常跑，但web ui还是没日志，hadoop上看原因依然是“java.util.concurrent.CompletionException: org.apache.flink.util.FlinkException: The file STDOUT is not available on the TaskExecutor...”，但任务不会挂掉。如果加日志配置的话，不仅web ui没日志，hadoop也没日志详情了（用dlink-client-hadoop.jar也是如此），没日志的话有啥问题我就会抓瞎。现在能正常跑任务就行，我再研究研究

**Comment by ghost** [comment]
> 报错变了，现在是访问 jobmanager 超时。

访问jobmanager超时，是因为job挂了，主要是不知道为什么挂。总结一下就是：（1）不添加log4j.properties时，job运行一段时间会挂，webui无日志，Hadoop上的jobmanager.out日志显示：java.util.concurrent.CompletionException:org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor。（2）添加log4j.properties时，job运行一段时间会挂掉，webui和hadoop均无日志详情，仅有一行“任务提交成功”。
（3）无论哪一种情况，在dlink和webui上看，jobid都是一串0

**Comment by ghost** [comment]
> > 报错变了，现在是访问 jobmanager 超时。
> 
> 访问jobmanager超时，是因为job挂了，主要是不知道为什么挂。总结一下就是：（1）不添加log4j.properties时，job运行一段时间会挂，webui无日志，Hadoop上的jobmanager.out日志显示：java.util.concurrent.CompletionException:org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor。（2）添加log4j.properties时，job运行一段时间会挂掉，webui和hadoop均无日志详情，仅有一行“任务提交成功”。 （3）无论哪一种情况，在dlink和webui上看，jobid都是一串0

在ha模式下使用yarn-application提交，无法使用随机字符串作为jobid，是flink本身的问题。https://issues.apache.org/jira/browse/FLINK-19358

**Comment by aiwenmo** [comment]
> > 报错变了，现在是访问 jobmanager 超时。
> 
> 访问jobmanager超时，是因为job挂了，主要是不知道为什么挂。总结一下就是：（1）不添加log4j.properties时，job运行一段时间会挂，webui无日志，Hadoop上的jobmanager.out日志显示：java.util.concurrent.CompletionException:org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor。（2）添加log4j.properties时，job运行一段时间会挂掉，webui和hadoop均无日志详情，仅有一行“任务提交成功”。 （3）无论哪一种情况，在dlink和webui上看，jobid都是一串0

jobId 是一串0是正确的，日志相关配置文件建议都加在集群配置的 flink-conf 的路径下

**Comment by ghost** [comment]
> > > 报错变了，现在是访问 jobmanager 超时。
> > 
> > 
> > 访问jobmanager超时，是因为job挂了，主要是不知道为什么挂。总结一下就是：（1）不添加log4j.properties时，job运行一段时间会挂，webui无日志，Hadoop上的jobmanager.out日志显示：java.util.concurrent.CompletionException:org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor。（2）添加log4j.properties时，job运行一段时间会挂掉，webui和hadoop均无日志详情，仅有一行“任务提交成功”。 （3）无论哪一种情况，在dlink和webui上看，jobid都是一串0
> 
> jobId 是一串0是正确的，日志相关配置文件建议都加在集群配置的 flink-conf 的路径下

我加了所有配置文件，证明不是这方面的问题。好像是log4j依赖问题吧，我还不太懂，在学习中~

我从命令行直接提交任务，任务正常运行，日志如下：
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/tmp/nm-local-dir/usercache/dataxc/appcache/application_1661844080468_0029/filecache/12/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/share/hadoop/common/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

dlink异步提交，任务无法正常运行，有如下日志：
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/tmp/nm-local-dir/filecache/13/dlink-client-hadoop-0.6.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/tmp/nm-local-dir/filecache/12/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/share/hadoop/common/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (org.apache.flink.runtime.entrypoint.ClusterEntrypoint).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by aiwenmo** [comment]
![image](https://user-images.githubusercontent.com/32723967/190987341-10e08429-2609-4f10-909c-922a0dd3f924.png)

我这边TM和JM都有日志，就是把日志相关配置文件都放在集群配置的 flink-conf 的路径下

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/32723967/190987341-10e08429-2609-4f10-909c-922a0dd3f924.png)
> 
> 我这边TM和JM都有日志，就是把日志相关配置文件都放在集群配置的 flink-conf 的路径下

我把dlink-client-hadoop-0.6.7.jar换成flink-shaded-hadoop-3-uber.jar，日志就出来了。
不知道我编译dlink-client-hadoop-0.6.7.jar的那个环节出错了

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/32723967/190987341-10e08429-2609-4f10-909c-922a0dd3f924.png)
> 
> 我这边TM和JM都有日志，就是把日志相关配置文件都放在集群配置的 flink-conf 的路径下

原因是我编译dlink-client-hadoop-0.6.7.jar的时候没有排除slf4j-log4j12和log4j，排除后就好了。
